In [1]:
import pandas as pd

In [2]:
import sqlite3

In [6]:
sql = 'select * from results'

In [4]:
con = sqlite3.connect('../players.db')

In [7]:
df = pd.read_sql(sql, con)

In [8]:
df

,index,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...,...
506,506,2019,14,Doubles,"Niels Feijen, Jayson Shaw",5,4,"Justin Bergman, Billy Thorpe",1
507,507,2019,15,Singles,Jayson Shaw,3,5,Billy Thorpe,0
508,508,2019,16,Singles,Eklent Kaçi,5,1,Tyler Styer,1
509,509,2019,17,Singles,Alexander Kazakis,3,5,Shane Van Boening,0
510,510,2019,18,Singles,Joshua Filler,3,5,Skyler Woodward,0