In [1]:
import pandas as pd

In [2]:
import sqlite3

In [3]:
sql = 'select * from results'

In [4]:
con = sqlite3.connect('players.db')

In [5]:
df = pd.read_sql(sql,con)

In [6]:
df = df.drop('index',axis=1)

In [7]:
df

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
520,2020,10,Singles,Jayson Shaw,5,3,Billy Thorpe,1
521,2020,11,Doubles,"Albin Ouschan, Joshua Filler",5,2,"Shane Van Boening, Skyler Woodward",1
522,2020,12,Singles,Joshua Filler,5,0,Skyler Woodward,1
523,2020,13,Doubles,"Albin Ouschan, Fedor Gorst",3,5,"Billy Thorpe, Chris Robinson",0
524,2020,14,Singles,Jayson Shaw,5,3,Shane Van Boening,1

In [8]:
f = pd.read_excel('C:\\Users\\rucku\\Desktop\\Coding Projects\\mosconi\\2020-2021 Mosconi cup results.xlsx',sheet_name=1)

In [19]:
f['Format'] = f['Europe'].str.extract(r'([A-Z][a-z]+)')

In [24]:
f.head()

                  Europe Scores                   America   Format
0     Teams\nTeam Europe    2–5           Teams\nTeam USA    Teams
1  DoublesOuschan & Kaçi    4–5   DoublesStyer & Reinhold  Doubles
2   SinglesJoshua Filler    5–2  SinglesShane Van Boening  Singles
3  DoublesAlcaide & Shaw    5–0   DoublesWoodward & Jones  Doubles
4     SinglesJayson Shaw    5–3  SinglesShane Van Boening  Singles

In [28]:
f['European_player'] = f['Europe'].str.extract(r'[A-Z][a-z]+\n?([A-Z].+)')

In [30]:
f['American_player'] = f['America'].str.extract(r'[A-Z][a-z]+\n?([A-Z].+)')

In [31]:
f

,Europe,Scores,America,Format,European_player,American_player
0,Teams\nTeam Europe,2–5,Teams\nTeam USA,Teams,Team Europe,Team USA
1,DoublesOuschan & Kaçi,4–5,DoublesStyer & Reinhold,Doubles,Ouschan & Kaçi,Styer & Reinhold
2,SinglesJoshua Filler,5–2,SinglesShane Van Boening,Singles,Joshua Filler,Shane Van Boening
3,DoublesAlcaide & Shaw,5–0,DoublesWoodward & Jones,Doubles,Alcaide & Shaw,Woodward & Jones
4,SinglesJayson Shaw,5–3,SinglesShane Van Boening,Singles,Jayson Shaw,Shane Van Boening
5,SinglesAlbin Ouschan,3–5,SinglesSkyler Woodward,Singles,Albin Ouschan,Skyler Woodward
6,DoublesOuschan & Shaw,4–5,DoublesVan Boening & Woodward,Doubles,Ouschan & Shaw,Van Boening & Woodward
7,SinglesJoshua Filler,3–5,SinglesTyler Styer,Singles,Joshua Filler,Tyler Styer
8,DoublesAlcaide & Kaçi,5–4,DoublesReinhold & Jones,Doubles,Alcaide & Kaçi,Reinhold & Jones
9,SinglesJayson Shaw,5–2,SinglesChris Reinhold,Singles,Jayson Shaw,Chris Reinhold
10,DoublesShaw & Filler,5–2,DoublesStyer & Woodward,Doubles,Shaw & Filler,Styer & Woodward
11,SinglesEklent Kaçi,5–3,SinglesShane Van Boening,Singles,Eklent Kaçi,Shane Van Boening
12,DoublesOuschan & Alcaide,5–1,DoublesStyer & Van Boening,Doubles,Ouschan & Alcaide,Styer & Van Boening
13,SinglesDavid Alcaide,5–4,SinglesJeremy Jones,Singles,David Alcaide,Jeremy Jones
14,DoublesShaw & Filler,2021-05-04 00:00:00,DoublesWoodward & Van Boening,Doubles,Shaw & Filler,Woodward & Van Boening
15,SinglesJayson Shaw,2–5,SinglesSkyler Woodward,Singles,Jayson Shaw,Skyler Woodward
16,SinglesJoshua Filler,5–4,SinglesShane Van Boening,Singles,Joshua Filler,Shane Van Boening

In [38]:
n = f['Scores'].str.extract(r'(\d)–(\d)')

In [41]:
n.columns=['European_score','American_score']

In [54]:
n.at[14,'European_score']=5

In [56]:
n.at[14,'American_score']=4

In [61]:
f = pd.concat([f,n],axis=1)

In [62]:
f.drop('Scores',axis=1,inplace=True)

In [64]:
f['Year']= '2021'

In [68]:
f = f[['Format', 'European_player', 'American_player',
       'European_score', 'American_score', 'Year']]

In [69]:
f

,Format,European_player,American_player,European_score,American_score,Year
0,Teams,Team Europe,Team USA,2,5,2021
1,Doubles,Ouschan & Kaçi,Styer & Reinhold,4,5,2021
2,Singles,Joshua Filler,Shane Van Boening,5,2,2021
3,Doubles,Alcaide & Shaw,Woodward & Jones,5,0,2021
4,Singles,Jayson Shaw,Shane Van Boening,5,3,2021
5,Singles,Albin Ouschan,Skyler Woodward,3,5,2021
6,Doubles,Ouschan & Shaw,Van Boening & Woodward,4,5,2021
7,Singles,Joshua Filler,Tyler Styer,3,5,2021
8,Doubles,Alcaide & Kaçi,Reinhold & Jones,5,4,2021
9,Singles,Jayson Shaw,Chris Reinhold,5,2,2021
10,Doubles,Shaw & Filler,Styer & Woodward,5,2,2021
11,Singles,Eklent Kaçi,Shane Van Boening,5,3,2021
12,Doubles,Ouschan & Alcaide,Styer & Van Boening,5,1,2021
13,Singles,David Alcaide,Jeremy Jones,5,4,2021
14,Doubles,Shaw & Filler,Woodward & Van Boening,5,4,2021
15,Singles,Jayson Shaw,Skyler Woodward,2,5,2021
16,Singles,Joshua Filler,Shane Van Boening,5,4,2021

In [71]:
f['Match'] = range(1, 18, 1)

<ipython-input-71-9754702c14a8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f['Match'] = range(1, 18, 1)

In [72]:
f

,Format,European_player,American_player,European_score,American_score,Year,Match
0,Teams,Team Europe,Team USA,2,5,2021,1
1,Doubles,Ouschan & Kaçi,Styer & Reinhold,4,5,2021,2
2,Singles,Joshua Filler,Shane Van Boening,5,2,2021,3
3,Doubles,Alcaide & Shaw,Woodward & Jones,5,0,2021,4
4,Singles,Jayson Shaw,Shane Van Boening,5,3,2021,5
5,Singles,Albin Ouschan,Skyler Woodward,3,5,2021,6
6,Doubles,Ouschan & Shaw,Van Boening & Woodward,4,5,2021,7
7,Singles,Joshua Filler,Tyler Styer,3,5,2021,8
8,Doubles,Alcaide & Kaçi,Reinhold & Jones,5,4,2021,9
9,Singles,Jayson Shaw,Chris Reinhold,5,2,2021,10
10,Doubles,Shaw & Filler,Styer & Woodward,5,2,2021,11
11,Singles,Eklent Kaçi,Shane Van Boening,5,3,2021,12
12,Doubles,Ouschan & Alcaide,Styer & Van Boening,5,1,2021,13
13,Singles,David Alcaide,Jeremy Jones,5,4,2021,14
14,Doubles,Shaw & Filler,Woodward & Van Boening,5,4,2021,15
15,Singles,Jayson Shaw,Skyler Woodward,2,5,2021,16
16,Singles,Joshua Filler,Shane Van Boening,5,4,2021,17

In [73]:
f['Europe_won'] = f['European_score']>f['American_score']

In [75]:
f['Europe_won'] = f['Europe_won'].apply(lambda x: 1 if x == True else 0)

In [77]:
f = f[['Year', 'Match', 'Format', 'European_player', 'European_score',
       'American_score', 'American_player', 'Europe_won']]

In [78]:
f.head(2)

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,2021,1,Teams,Team Europe,2,5,Team USA,0
1,2021,2,Doubles,Ouschan & Kaçi,4,5,Styer & Reinhold,0

In [79]:
df.tail(3)

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
522,2020,12,Singles,Joshua Filler,5,0,Skyler Woodward,1
523,2020,13,Doubles,"Albin Ouschan, Fedor Gorst",3,5,"Billy Thorpe, Chris Robinson",0
524,2020,14,Singles,Jayson Shaw,5,3,Shane Van Boening,1

In [80]:
new = pd.concat([df,f])

In [81]:
new = new.reset_index()

In [82]:
new = new.drop('index',axis=1)

In [83]:
new

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
537,2021,13,Doubles,Ouschan & Alcaide,5,1,Styer & Van Boening,1
538,2021,14,Singles,David Alcaide,5,4,Jeremy Jones,1
539,2021,15,Doubles,Shaw & Filler,5,4,Woodward & Van Boening,1
540,2021,16,Singles,Jayson Shaw,2,5,Skyler Woodward,0
541,2021,17,Singles,Joshua Filler,5,4,Shane Van Boening,1

In [84]:
new.to_sql('results', con, if_exists = 'replace')

In [85]:
new

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
537,2021,13,Doubles,Ouschan & Alcaide,5,1,Styer & Van Boening,1
538,2021,14,Singles,David Alcaide,5,4,Jeremy Jones,1
539,2021,15,Doubles,Shaw & Filler,5,4,Woodward & Van Boening,1
540,2021,16,Singles,Jayson Shaw,2,5,Skyler Woodward,0
541,2021,17,Singles,Joshua Filler,5,4,Shane Van Boening,1