In [1]:
import pandas as pd

In [2]:
import sqlite3

In [3]:
sql = 'select * from results'

In [4]:
con = sqlite3.connect('players.db')

In [5]:
df = pd.read_sql(sql,con)

In [77]:
df = df.drop('index',axis=1)

In [78]:
df

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
506,2019,14,Doubles,"Niels Feijen, Jayson Shaw",5,4,"Justin Bergman, Billy Thorpe",1
507,2019,15,Singles,Jayson Shaw,3,5,Billy Thorpe,0
508,2019,16,Singles,Eklent Kaçi,5,1,Tyler Styer,1
509,2019,17,Singles,Alexander Kazakis,3,5,Shane Van Boening,0
510,2019,18,Singles,Joshua Filler,3,5,Skyler Woodward,0

In [62]:
f = pd.read_excel('C:\\Users\\rucku\\Desktop\\Coding Projects\\mosconi\\2020-2021 Mosconi cup results.xlsx')

In [63]:
f['Format'] = f['Europe'].str.split('\n').str.get(0)

In [64]:
f

,Europe,Scores,America,Format
0,Teams\nTeam Europe,3–5,Teams\nTeam USA,Teams
1,Doubles\nJoshua Filler\nFedor Gorst,5–2,Doubles\nShane Van Boening\nCorey Deuel,Doubles
2,Singles\nEklent Kaçi,5–4,Singles\nChris Robinson,Singles
3,Doubles\nJayson Shaw\nAlbin Ouschan,5–2,Doubles\nSkyler Woodward\nBilly Thorpe,Doubles
4,Singles\nAlbin Ouschan,4–5,Singles\nShane Van Boening,Singles
5,Singles\nJayson Shaw,5–4,Singles\nShane Van Boening,Singles
6,Doubles\nJayson Shaw\nJoshua Filler,5–4,Doubles\nSkyler Woodward\nChris Robinson,Doubles
7,Singles\nFedor Gorst,5–2,Singles\nCorey Deuel,Singles
8,Doubles\nEklent Kaçi\nAlbin Ouschan,5–4,Doubles\nShane Van Boening\nBilly Thorpe,Doubles
9,Singles\nJayson Shaw,5–3,Singles\nBilly Thorpe,Singles
10,Doubles\nAlbin Ouschan\nJoshua Filler,5–2,Doubles\nShane Van Boening\nSkyler Woodward,Doubles
11,Singles\nJoshua Filler,5–0,Singles\nSkyler Woodward,Singles
12,Doubles\nAlbin Ouschan\nFedor Gorst,3–5,Doubles\nBilly Thorpe\nChris Robinson,Doubles
13,Singles\nJayson Shaw,5–3,Singles\nShane Van Boening,Singles

In [65]:
f['Europe'] = f['Europe'].str.replace('Teams\n','').str.replace('Doubles\n','').str.replace('Singles\n','').str.replace('\n',', ')

In [66]:
f['America'] = f['America'].str.replace('Teams\n','').str.replace('Doubles\n','').str.replace('Singles\n','').str.replace('\n',', ')

In [67]:
f['European_score'] = f['Scores'].str.split('–').str.get(0)

In [68]:
f['American_score'] = f['Scores'].str.split('–').str.get(1)

In [69]:
f.drop('Scores',axis=1,inplace=True)

In [72]:
f.columns=['European_player','American_player','Format','European_score', 'American_score']

In [73]:
f['Year']= '2020'

In [82]:
f

,European_player,American_player,Format,European_score,American_score,Year
0,Team Europe,Team USA,Teams,3,5,2020
1,"Joshua Filler, Fedor Gorst","Shane Van Boening, Corey Deuel",Doubles,5,2,2020
2,Eklent Kaçi,Chris Robinson,Singles,5,4,2020
3,"Jayson Shaw, Albin Ouschan","Skyler Woodward, Billy Thorpe",Doubles,5,2,2020
4,Albin Ouschan,Shane Van Boening,Singles,4,5,2020
5,Jayson Shaw,Shane Van Boening,Singles,5,4,2020
6,"Jayson Shaw, Joshua Filler","Skyler Woodward, Chris Robinson",Doubles,5,4,2020
7,Fedor Gorst,Corey Deuel,Singles,5,2,2020
8,"Eklent Kaçi, Albin Ouschan","Shane Van Boening, Billy Thorpe",Doubles,5,4,2020
9,Jayson Shaw,Billy Thorpe,Singles,5,3,2020
10,"Albin Ouschan, Joshua Filler","Shane Van Boening, Skyler Woodward",Doubles,5,2,2020
11,Joshua Filler,Skyler Woodward,Singles,5,0,2020
12,"Albin Ouschan, Fedor Gorst","Billy Thorpe, Chris Robinson",Doubles,3,5,2020
13,Jayson Shaw,Shane Van Boening,Singles,5,3,2020

In [87]:
f['Match'] = range(1, 15, 1)

In [94]:
f['Europe_won'] = f['European_score']>f['American_score']

In [95]:
f

,European_player,American_player,Format,European_score,American_score,Year,Match,Europe_won
0,Team Europe,Team USA,Teams,3,5,2020,1,False
1,"Joshua Filler, Fedor Gorst","Shane Van Boening, Corey Deuel",Doubles,5,2,2020,2,True
2,Eklent Kaçi,Chris Robinson,Singles,5,4,2020,3,True
3,"Jayson Shaw, Albin Ouschan","Skyler Woodward, Billy Thorpe",Doubles,5,2,2020,4,True
4,Albin Ouschan,Shane Van Boening,Singles,4,5,2020,5,False
5,Jayson Shaw,Shane Van Boening,Singles,5,4,2020,6,True
6,"Jayson Shaw, Joshua Filler","Skyler Woodward, Chris Robinson",Doubles,5,4,2020,7,True
7,Fedor Gorst,Corey Deuel,Singles,5,2,2020,8,True
8,"Eklent Kaçi, Albin Ouschan","Shane Van Boening, Billy Thorpe",Doubles,5,4,2020,9,True
9,Jayson Shaw,Billy Thorpe,Singles,5,3,2020,10,True
10,"Albin Ouschan, Joshua Filler","Shane Van Boening, Skyler Woodward",Doubles,5,2,2020,11,True
11,Joshua Filler,Skyler Woodward,Singles,5,0,2020,12,True
12,"Albin Ouschan, Fedor Gorst","Billy Thorpe, Chris Robinson",Doubles,3,5,2020,13,False
13,Jayson Shaw,Shane Van Boening,Singles,5,3,2020,14,True

In [100]:
f['Europe_won'] = f['Europe_won'].apply(lambda x: 1 if x == True else 0)

In [105]:
f = f[['Year', 'Match', 'Format', 'European_player', 'European_score',
       'American_score', 'American_player', 'Europe_won']]

In [108]:
f.head(2)

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,2020,1,Teams,Team Europe,3,5,Team USA,0
1,2020,2,Doubles,"Joshua Filler, Fedor Gorst",5,2,"Shane Van Boening, Corey Deuel",1

In [106]:
df.tail(3)

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
508,2019,16,Singles,Eklent Kaçi,5,1,Tyler Styer,1
509,2019,17,Singles,Alexander Kazakis,3,5,Shane Van Boening,0
510,2019,18,Singles,Joshua Filler,3,5,Skyler Woodward,0

In [112]:
new = pd.concat([df,f])

In [115]:
new = new.reset_index()

In [118]:
new = new.drop('index',axis=1)

In [119]:
new

,Year,Match,Format,European_player,European_score,American_score,American_player,Europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
520,2020,10,Singles,Jayson Shaw,5,3,Billy Thorpe,1
521,2020,11,Doubles,"Albin Ouschan, Joshua Filler",5,2,"Shane Van Boening, Skyler Woodward",1
522,2020,12,Singles,Joshua Filler,5,0,Skyler Woodward,1
523,2020,13,Doubles,"Albin Ouschan, Fedor Gorst",3,5,"Billy Thorpe, Chris Robinson",0
524,2020,14,Singles,Jayson Shaw,5,3,Shane Van Boening,1

In [120]:
# new.to_sql('results',con,if_exists = 'replace')