In [3]:
import pandas as pd

In [4]:
pkl=r'C:\Users\andrew\Desktop\mosconi\mosconi_1998_2015_inc_pkls'
df= pd.read_pickle(pkl)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 333 entries, 0 to 17
Data columns (total 6 columns):
Format             333 non-null object
European_player    333 non-null object
European_score     333 non-null object
American_score     333 non-null object
American_player    333 non-null object
Europe_won         333 non-null bool
dtypes: bool(1), object(5)
memory usage: 15.9+ KB

In [6]:
df.shape

(333, 6)

In [7]:
df.head()

,Format,European_player,European_score,American_score,American_player,Europe_won
0,Doubles,Mika Immonen Ralf Souquet,7,5,Johnny Archer Nick Varner,True
1,Doubles,Oliver Ortmann Steve Knight,7,6,James Rempe Earl Strickland,True
2,Doubles,Fabio Petroni Steve Davis,5,7,Kim Davenport Reed Pierce,False
3,Doubles,Mika Immonen Ralf Souquet,7,3,James Rempe Earl Strickland,True
4,Doubles,Steve Davis Fabio Petroni,3,7,Nick Varner Johnny Archer,False

In [8]:
df.describe()

,Format,European_player,European_score,American_score,American_player,Europe_won
count,333,333,333,333,333,333
unique,5,102,8,8,101,2
top,Singles,Mika Immonen,5,5,Johnny Archer,True
freq,181,27,126,120,28,169

In [9]:
df.Format.unique()

array(['Doubles', 'Singles', 'Teams', 'Trebles', 'Triples'], dtype=object)

In [10]:
trips = df.Format =='Triples' 
df[trips]

,Format,European_player,European_score,American_score,American_player,Europe_won
16,Triples,Imran Majid Thomas Engert Nick van den Berg,5,6,Corey Deuel Earl Strickland John Schmidt,False
17,Triples,Ralf Souquet Mika Immonen David Alcaide,1,6,Johnny Archer Rodney Morris Mike Davis,False

Note: Found it unusual that there are five types of format. Turns out there are four triples matches: two named 'Triples' and two named 'Trebles'

Find a way to loop thru all players and make the boolean queries to return their matches played

In [11]:
with open('euro_players_scrape.txt', 'r') as rf:
    euro_players=[]
    for line in rf:
        n=line.split('  ')
        euro_players.append(n[0])
with open('am_players_scrape.txt', 'r') as rf:
    am_players=[]
    for line in rf:
        n=line.split('  ')
        am_players.append(n[0])

In [12]:
am_players.remove('Ã“scar DomÃ\xadnguez')
am_players.append('Oscar Dominguez')
am_players.remove('Buddy Hall')
am_players.remove('Don Wardell ')

In [13]:
svb = df['American_player'].str.contains('Shane Van Boening')
earl = df['American_player'].str.contains('Earl Strickland')
hatch = df['American_player'].str.contains('Dennis Hatch')
albin = df['European_player'].str.contains('Albin Ouschan')
woodward = df['American_player'].str.contains('Woodward')
niels = df['European_player'].str.contains('Niels')

In [14]:
singles = df['Format']=='Singles'
doubles = df['Format']=='Doubles'
teams = df['Format']=='Teams'


europe_won = df['Europe_won'] == True
america_won = df['Europe_won'] == False

In [15]:
df[earl&(df['Europe_won'] == False)]

,Format,European_player,European_score,American_score,American_player,Europe_won
7,Singles,Steve Knight,3,7,Earl Strickland,False
10,Doubles,Steve Knight Oliver Ortmann,6,7,Earl Strickland Kim Davenport,False
15,Singles,Mika Immonen,4,7,Earl Strickland,False
1,Doubles,Oliver Ortmann Alex Lely,2,5,Earl Strickland James Rempe,False
11,Doubles,Steve Davis Alex Lely,3,5,Earl Strickland Johnny Archer,False
2,Doubles,Steve Davis Steve Knight,2,5,Earl Strickland Corey Deuel,False
11,Doubles,Steve Davis Mika Immonen,1,5,Earl Strickland Jeremy Jones,False
14,Singles,Ralf Souquet,1,5,Earl Strickland,False
20,Singles,Thomas Engert,2,5,Earl Strickland,False
2,Doubles,Steve Davis Ralf Souquet,2,5,Earl Strickland Jeremy Jones,False
3,Doubles,Steve Davis Ralf Souquet,2,5,Earl Strickland Jeremy Jones,False
10,Singles,Niels Feijen,2,5,Earl Strickland,False
6,Singles,Marcus Chamat,2,5,Earl Strickland,False
10,Doubles,Oliver Ortmann Ralf Souquet,1,5,Earl Strickland Jeremy Jones,False
3,Doubles,Steve Davis Nick van den Berg,4,5,Earl Strickland Jeremy Jones,False
6,Doubles,Steve Davis Nick van den Berg,3,5,Tony Robles Earl Strickland,False
16,Singles,Nick van den Berg,4,5,Earl Strickland,False
2,Doubles,Mika Immonen Marcus Chamat,4,5,Earl Strickland Rodney Morris,False
5,Doubles,Oliver Ortmann Thomas Engert,4,5,Earl Strickland Rodney Morris,False
11,Doubles,Mika Immonen Marcus Chamat,0,5,Earl Strickland Rodney Morris,False
4,Doubles,Mika Immonen Marcus Chamat,4,5,Earl Strickland Rodney Morris,False
9,Doubles,Alex Lely Raj Hundal,2,5,Earl Strickland Rodney Morris,False
12,Doubles,Marcus Chamat Mika Immonen,2,5,Rodney Morris Earl Strickland,False
13,Singles,Marcus Chamat,2,5,Earl Strickland,False
2,Trebles,Imran Majid Thomas Engert Nick van den Berg,2,6,Corey Deuel Earl Strickland Rodney Morris,False
13,Singles,Thomas Engert,4,7,Earl Strickland,False
16,Triples,Imran Majid Thomas Engert Nick van den Berg,5,6,Corey Deuel Earl Strickland John Schmidt,False
3,Doubles,Tony Drago Konstantin Stepanov,5,6,Earl Strickland Corey Deuel,False
9,Doubles,Daryl Peach Ralf Souquet,5,6,Rodney Morris Earl Strickland,False
17,Singles,Daryl Peach,3,6,Earl Strickland,False
3,Doubles,Tony Drago Mark Gray,3,5,Earl Strickland Johnny Archer,False
5,Singles,Tony Drago,4,5,Earl Strickland,False
7,Doubles,Darren Appleton Mika Immonen,5,6,Earl Strickland Shane Van Boening,False

In [16]:
d={}
for player in am_players:
    d[player] = df['American_player'].str.contains(player)

In [17]:
def singleswinloss(player,country):
    if 'a' in country:
        win=df[america_won&singles&player].shape[0]
        loss=df[player&~america_won&singles].shape[0]
    else:
        loss=df[player&america_won&singles].shape[0]
        win=df[player&~america_won&singles].shape[0]        
    swl='{}-{}'.format(win,loss)
    return(wl)
def doubleswinloss(player,country):
    if 'a' in country:
        win=df[player&america_won&doubles].shape[0]
        loss=df[player&~america_won&doubles].shape[0]
    else:
        loss=df[player&america_won&doubles].shape[0]
        win=df[player&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(win,loss)
    return(wl)
def combinedwinloss(player,country):
    if 'a' in country:
        dwin=df[player&america_won&doubles].shape[0]
        dloss=df[player&~america_won&doubles].shape[0]
        swin=df[player&america_won&singles].shape[0]
        sloss=df[player&~america_won&singles].shape[0]
    else:
        dloss=df[player&america_won&doubles].shape[0]
        dwin=df[player&~america_won&doubles].shape[0]
        sloss=df[player&america_won&singles].shape[0]
        swin=df[player&~america_won&singles].shape[0]
    win=dwin+swin
    loss=dloss+sloss
    cwl='{}-{}'.format(win,loss)
    return(wl)

In [18]:
def winloss(player, country):
    
    #singles
    if 'a' in country:
        win=df[america_won&singles&player].shape[0]
        loss=df[player&~america_won&singles].shape[0]
    else:
        loss=df[player&america_won&singles].shape[0]
        win=df[player&~america_won&singles].shape[0]        
    swl='{}-{}'.format(win,loss)
    spct=win*100/(win+loss)

    #doubles
    if 'a' in country:
        win=df[player&america_won&doubles].shape[0]
        loss=df[player&~america_won&doubles].shape[0]
    else:
        loss=df[player&america_won&doubles].shape[0]
        win=df[player&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(win,loss)
    dpct=win*100/(win+loss)

    #combined
    if 'a' in country:
        dwin=df[player&america_won&doubles].shape[0]
        dloss=df[player&~america_won&doubles].shape[0]
        swin=df[player&america_won&singles].shape[0]
        sloss=df[player&~america_won&singles].shape[0]
    else:
        dloss=df[player&america_won&doubles].shape[0]
        dwin=df[player&~america_won&doubles].shape[0]
        sloss=df[player&america_won&singles].shape[0]
        swin=df[player&~america_won&singles].shape[0]
    win=dwin+swin
    loss=dloss+sloss
    cwl='{}-{}'.format(win,loss)
    cpct=win*100/(win+loss)
    print("singles: {}   pct:{}   doubles: {}  pct:{}    combined: {}  pct:{}".format(swl,spct,dwl,dpct,cwl,cpct))
    return(swl,dwl,cwl)

In [28]:
winloss(hatch,'a')

singles: 4-3   pct:57.142857142857146   doubles: 5-7  pct:41.666666666666664    combined: 9-10  pct:47.36842105263158

('4-3', '5-7', '9-10')

In [29]:
def winlosslist(player, country):
    
    #singles
    if 'a' in country:
        win=df[america_won&singles&player].shape[0]
        loss=df[player&~america_won&singles].shape[0]
    else:
        loss=df[player&america_won&singles].shape[0]
        win=df[player&~america_won&singles].shape[0]        
    swl='{}-{}'.format(win,loss)
    spct=win*100/(win+loss)

    #doubles
    if 'a' in country:
        win=df[player&america_won&doubles].shape[0]
        loss=df[player&~america_won&doubles].shape[0]
    else:
        loss=df[player&america_won&doubles].shape[0]
        win=df[player&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(win,loss)
    dpct=win*100/(win+loss)

    #combined
    if 'a' in country:
        dwin=df[player&america_won&doubles].shape[0]
        dloss=df[player&~america_won&doubles].shape[0]
        swin=df[player&america_won&singles].shape[0]
        sloss=df[player&~america_won&singles].shape[0]
    else:
        dloss=df[player&america_won&doubles].shape[0]
        dwin=df[player&~america_won&doubles].shape[0]
        sloss=df[player&america_won&singles].shape[0]
        swin=df[player&~america_won&singles].shape[0]
    win=dwin+swin
    loss=dloss+sloss
    cwl='{}-{}'.format(win,loss)
    cpct=win*100/(win+loss)
#     print("singles: {}   pct:{}   doubles: {}  pct:{}    combined: {}  pct:{}".format(swl,spct,dwl,dpct,cwl,cpct))
#     return(swl,dwl,cwl)
    l=[swl,spct,dwl,dpct,cwl,cpct]
    print(l)
    return(l)

In [37]:
def wl(win,loss):
    swl='{}-{}'.format(win,loss)
    return(swl)
def winpct(win,loss):
    pct=win*100/(win+loss)
    return(pct)
def wlpct(win,loss):
    wl = '{}-{}'.format(win,loss)
    pct = win*100/(win+loss)
    return(wl,pct)

In [38]:
wlpct(5,2)

('5-2', 71.42857142857143)

In [30]:
winlosslist(hatch,'am')

['4-3', 57.142857142857146, '5-7', 41.666666666666664, '9-10', 47.36842105263158]

['4-3',
 57.142857142857146,
 '5-7',
 41.666666666666664,
 '9-10',
 47.36842105263158]

In [22]:
stat_l = []
for player in am_players:
    try:
        unit = winlosslist(d[player],'am')
        stat_l.append(unit)
    except:
        pass
stat_l

[[0      True
  1     False
  2     False
  3     False
  4      True
  5     False
  6      True
  7     False
  8     False
  9     False
  10    False
  11     True
  12    False
  13    False
  14    False
  15    False
  16     True
  17    False
  18    False
  19    False
  20    False
  21     True
  0      True
  1     False
  2     False
  3      True
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '15-13',
  53.57142857142857,
  '27-20',
  57.4468085106383,
  '42-33',
  56.0],
 [0     False
  1      True
  2     False
  3      True
  4     False
  5     False
  6     False
  7      True
  8     False
  9     False
  10     True
  11    False
  12    False
  13    False
  14    False
  15     True
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1      True
  2     False
  3     False
  4      True
  5     False
  6     False
  7      True
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '11-9',
  55.0,
  '20-12',
  62.5,
  '31-21',
  59.61538461538461],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '9-8',
  52.94117647058823,
  '11-15',
  42.30769230769231,
  '20-23',
  46.51162790697674],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4      True
  5     False
  6     False
  7      True
  8     False
  9      True
  10    False
  11    False
  12    False
  13    False
  14     True
  15     True
  0     False
  1     False
  2     False
  3      True
  4      True
  5     False
  6     False
  7      True
  8     False
  9      True
  10    False
  11    False
  12    False
  13     True
  14    False
  15    False
  16     True
  17    False
  Name: American_player, dtype: bool,
  '10-14',
  41.666666666666664,
  '11-11',
  50.0,
  '21-25',
  45.65217391304348],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6      True
  7     False
  8     False
  9      True
  10    False
  11    False
  12     True
  13    False
  14    False
  15    False
  0     False
  1      True
  2     False
  3     False
  4     False
  5     False
  6     False
  7      True
  8     False
  9     False
  10     True
  11     True
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '6-6',
  50.0,
  '13-12',
  52.0,
  '19-18',
  51.351351351351354],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2      True
  3     False
  4     False
  5      True
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '6-7',
  46.15384615384615,
  '10-9',
  52.63157894736842,
  '16-16',
  50.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '6-2',
  75.0,
  '6-7',
  46.15384615384615,
  '12-9',
  57.142857142857146],
 [0      True
  1     False
  2     False
  3     False
  4      True
  5     False
  6     False
  7     False
  8     False
  9      True
  10    False
  11     True
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18     True
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-4',
  20.0,
  '5-4',
  55.55555555555556,
  '6-8',
  42.857142857142854],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1      True
  2     False
  3     False
  4     False
  5     False
  6      True
  7     False
  8     False
  9      True
  10    False
  11    False
  12     True
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-4',
  20.0,
  '2-6',
  25.0,
  '3-10',
  23.076923076923077],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '4-3',
  57.142857142857146,
  '5-7',
  41.666666666666664,
  '9-10',
  47.36842105263158],
 [0     False
  1     False
  2      True
  3     False
  4     False
  5      True
  6     False
  7     False
  8     False
  9     False
  10     True
  11    False
  12    False
  13     True
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20     True
  21    False
  0      True
  1     False
  2     False
  3      True
  4     False
  5     False
  6      True
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '4-0',
  100.0,
  '4-2',
  66.66666666666667,
  '8-2',
  80.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5      True
  6     False
  7     False
  8      True
  9     False
  10    False
  11    False
  12    False
  13     True
  14    False
  15    False
  0     False
  1     False
  2      True
  3     False
  4     False
  5      True
  6     False
  7     False
  8     False
  9     False
  10     True
  11    False
  12    False
  13    False
  14     True
  15     True
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-4',
  20.0,
  '2-2',
  50.0,
  '3-6',
  33.333333333333336],
 [0     False
  1      True
  2     False
  3      True
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12     True
  13    False
  14     True
  15    False
  16    False
  17    False
  18    False
  19     True
  20    False
  21    False
  0     False
  1      True
  2     False
  3     False
  4      True
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-2',
  33.333333333333336,
  '2-4',
  33.333333333333336,
  '3-6',
  33.333333333333336],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2      True
  3     False
  4     False
  5      True
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool, '1-3', 25.0, '3-3', 50.0, '4-6', 40.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-1',
  50.0,
  '2-1',
  66.66666666666667,
  '3-2',
  60.0],
 [0     False
  1     False
  2      True
  3     False
  4     False
  5      True
  6     False
  7     False
  8      True
  9     False
  10    False
  11    False
  12     True
  13    False
  14    False
  15    False
  16    False
  17     True
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '2-0',
  100.0,
  '1-2',
  33.333333333333336,
  '3-2',
  60.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '0-1',
  0.0,
  '2-1',
  66.66666666666667,
  '2-2',
  50.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-3',
  25.0,
  '2-3',
  40.0,
  '3-6',
  33.333333333333336],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7      True
  8     False
  9     False
  10     True
  11    False
  12     True
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  Name: American_player, dtype: bool,
  '1-2',
  33.333333333333336,
  '0-5',
  0.0,
  '1-7',
  12.5],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3      True
  4     False
  5      True
  6     False
  7     False
  8      True
  9     False
  10    False
  11    False
  12     True
  13    False
  14    False
  15    False
  16    False
  17     True
  Name: American_player, dtype: bool,
  '0-2',
  0.0,
  '2-1',
  66.66666666666667,
  '2-3',
  40.0],
 [0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  16    False
  17    False
  18    False
  19    False
  20    False
  21    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
        ...
  4     False
  5     False
  6     False
  7     False
  8     False
  9     False
  10    False
  11    False
  12    False
  13    False
  14    False
  15    False
  0     False
  1     False
  2     False
  3     False
  4     False
  5     False
  6     False
  7     False
  8     False

In [24]:
stat_cols = ['player', 'singles', 'singles_pct', 'doubles', 'doubles_pct', 'combined', 'combined_pct']

In [ ]:
stats_df = pd.DataFrame(columns = stat_cols)
for player in am_players:
    try:
        print(player)
        print(winloss(d[player],'am'))
    except:
        pass