In [3]:
import pandas as pd

In [4]:
pkl=r'C:\Users\andrew\Desktop\mosconi\mosconi_1998_2015_inc_pkls'
df= pd.read_pickle(pkl)

In [8]:
df.describe()

,Format,European_player,European_score,American_score,American_player,Europe_won
count,333,333,333,333,333,333
unique,5,102,8,8,101,2
top,Singles,Mika Immonen,5,5,Johnny Archer,True
freq,181,27,126,120,28,169

In [9]:
df.Format.unique()

array(['Doubles', 'Singles', 'Teams', 'Trebles', 'Triples'], dtype=object)

In [10]:
trips = df.Format =='Triples' 
df[trips]

,Format,European_player,European_score,American_score,American_player,Europe_won
16,Triples,Imran Majid Thomas Engert Nick van den Berg,5,6,Corey Deuel Earl Strickland John Schmidt,False
17,Triples,Ralf Souquet Mika Immonen David Alcaide,1,6,Johnny Archer Rodney Morris Mike Davis,False

Note: Found it unusual that there are five types of format. Turns out there are four triples matches: two named 'Triples' and two named 'Trebles'

Find a way to loop thru all players and make the boolean queries to return their matches played

In [11]:
with open('euro_players_scrape.txt', 'r') as rf:
    euro_players=[]
    for line in rf:
        n=line.split('  ')
        euro_players.append(n[0])
with open('am_players_scrape.txt', 'r') as rf:
    am_players=[]
    for line in rf:
        n=line.split('  ')
        am_players.append(n[0])

In [106]:
#remove non-playing captains and fix oscar's name
am_players.remove('Ã“scar DomÃ\xadnguez')
am_players.append('Óscar Domínguez')
am_players.remove('Buddy Hall')
am_players.remove('Don Wardell')
euro_players.remove('Johan Ruijsink')

In [14]:
singles = df['Format']=='Singles'
doubles = df['Format']=='Doubles'
teams = df['Format']=='Teams'

europe_won = df['Europe_won'] == True
america_won = df['Europe_won'] == False

In [116]:
#create dict to index df by player
d={}
for player in am_players:
    d[player] = df['American_player'].str.contains(player)
for player in euro_players:
    d[player] = df['European_player'].str.contains(player)

In [142]:
players = am_players + euro_players

In [144]:
c=0
f=0
nodata=[]
hasdata=[]
for player in am_players:
    _=df[d[player]]
    if _.empty:
        f+=1
        nodata.append(player)
    else:
        c+=1
        hasdata.append(player)
print(c,f)

25 15

In [119]:
nodata

['Mark Wilson',
 'Lou Butera',
 'Mike Gulyassy',
 'Robert Hunter',
 'Mike Massey',
 'Dallas West',
 'C.J. Wiley',
 'John DiToro',
 'Paul Gerni',
 'Roger Griffis',
 'Danny Harriman',
 'Allen Hopkins',
 'Bobby Hunter',
 'Jeanette Lee',
 'Vivian Villarreal']

The above players have no matches from 1998 onwards (they played between 1994-1998)

In [17]:
def singleswinloss(player,country):
    if 'a' in country:
        win=df[america_won&singles&player].shape[0]
        loss=df[player&~america_won&singles].shape[0]
    else:
        loss=df[player&america_won&singles].shape[0]
        win=df[player&~america_won&singles].shape[0]        
    swl='{}-{}'.format(win,loss)
    return(wl)
def doubleswinloss(player,country):
    if 'a' in country:
        win=df[player&america_won&doubles].shape[0]
        loss=df[player&~america_won&doubles].shape[0]
    else:
        loss=df[player&america_won&doubles].shape[0]
        win=df[player&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(win,loss)
    return(wl)
def combinedwinloss(player,country):
    if 'a' in country:
        dwin=df[player&america_won&doubles].shape[0]
        dloss=df[player&~america_won&doubles].shape[0]
        swin=df[player&america_won&singles].shape[0]
        sloss=df[player&~america_won&singles].shape[0]
    else:
        dloss=df[player&america_won&doubles].shape[0]
        dwin=df[player&~america_won&doubles].shape[0]
        sloss=df[player&america_won&singles].shape[0]
        swin=df[player&~america_won&singles].shape[0]
    win=dwin+swin
    loss=dloss+sloss
    cwl='{}-{}'.format(win,loss)
    return(wl)

In [18]:
def winloss(player, country):
    
    #singles
    if 'a' in country:
        win=df[america_won&singles&player].shape[0]
        loss=df[player&~america_won&singles].shape[0]
    else:
        loss=df[player&america_won&singles].shape[0]
        win=df[player&~america_won&singles].shape[0]        
    swl='{}-{}'.format(win,loss)
    spct=win*100/(win+loss)

    #doubles
    if 'a' in country:
        win=df[player&america_won&doubles].shape[0]
        loss=df[player&~america_won&doubles].shape[0]
    else:
        loss=df[player&america_won&doubles].shape[0]
        win=df[player&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(win,loss)
    dpct=win*100/(win+loss)

    #combined
    if 'a' in country:
        dwin=df[player&america_won&doubles].shape[0]
        dloss=df[player&~america_won&doubles].shape[0]
        swin=df[player&america_won&singles].shape[0]
        sloss=df[player&~america_won&singles].shape[0]
    else:
        dloss=df[player&america_won&doubles].shape[0]
        dwin=df[player&~america_won&doubles].shape[0]
        sloss=df[player&america_won&singles].shape[0]
        swin=df[player&~america_won&singles].shape[0]
    win=dwin+swin
    loss=dloss+sloss
    cwl='{}-{}'.format(win,loss)
    cpct=win*100/(win+loss)
    print("singles: {}   pct:{}   doubles: {}  pct:{}    combined: {}  pct:{}".format(swl,spct,dwl,dpct,cwl,cpct))
    return(swl,dwl,cwl)

In [28]:
winloss(hatch,'a')

singles: 4-3   pct:57.142857142857146   doubles: 5-7  pct:41.666666666666664    combined: 9-10  pct:47.36842105263158

('4-3', '5-7', '9-10')

In [37]:
def wl(win,loss):
    swl='{}-{}'.format(win,loss)
    return(swl)
def winpct(win,loss):
    pct=win*100/(win+loss)
    return(pct)
def wlpct(win,loss):
    wl = '{}-{}'.format(win,loss)
    pct = win*100/(win+loss)
    return(wl,pct)

In [168]:
def winlosslist(player, country):
    
    #singles
    if 'a' in country:
        swin=df[america_won&singles&d[player]].shape[0]
        sloss=df[d[player]&~america_won&singles].shape[0]
    else:
        sloss=df[d[player]&america_won&singles].shape[0]
        swin=df[d[player]&~america_won&singles].shape[0]        
    swl='{}-{}'.format(swin,sloss)
    spct=swin*100/(swin+sloss)

    #doubles
    if 'a' in country:
        dwin=df[d[player]&america_won&doubles].shape[0]
        dloss=df[d[player]&~america_won&doubles].shape[0]
    else:
        dloss=df[d[player]&america_won&doubles].shape[0]
        dwin=df[d[player]&~america_won&doubles].shape[0] 
    dwl='{}-{}'.format(dwin,dloss)
    dpct=dwin*100/(dwin+dloss)

    #combined
    cwin=dwin+swin
    closs=dloss+sloss
    cwl='{}-{}'.format(cwin,closs)
    cpct=cwin*100/(cwin+closs)
    l=[player,country,swin,sloss,swl,round(spct,2),dwin,dloss,dwl,round(dpct,2),cwin,closs,cwl,round(cpct,2)]
    return(l)

In [159]:
def playerinfo(player,country):
    wl=winlosslist(player,country)
    frame=df[d[player]]
    return(frame)

In [169]:
stat_l = []
for player in am_players:
    try:
        unit = winlosslist(player,'America')
        stat_l.append(unit)
    except:
        pass
for player in euro_players:
    try:
        unit = winlosslist(player,'Europe')
        stat_l.append(unit)
    except:
        pass

['Johnny Archer', 'America', 15, 13, '15-13', 53.57, 27, 20, '27-20', 57.45, 42, 33, '42-33', 56.0]
['Earl Strickland', 'America', 11, 9, '11-9', 55.0, 20, 12, '20-12', 62.5, 31, 21, '31-21', 59.62]
['Rodney Morris', 'America', 9, 8, '9-8', 52.94, 11, 15, '11-15', 42.31, 20, 23, '20-23', 46.51]
['Shane Van Boening', 'America', 10, 14, '10-14', 41.67, 11, 11, '11-11', 50.0, 21, 25, '21-25', 45.65]
['Corey Deuel', 'America', 6, 6, '6-6', 50.0, 13, 12, '13-12', 52.0, 19, 18, '19-18', 51.35]
['Jeremy Jones', 'America', 6, 7, '6-7', 46.15, 10, 9, '10-9', 52.63, 16, 16, '16-16', 50.0]
['Charlie Williams', 'America', 6, 2, '6-2', 75.0, 6, 7, '6-7', 46.15, 12, 9, '12-9', 57.14]
['Nick Varner', 'America', 1, 4, '1-4', 20.0, 5, 4, '5-4', 55.56, 6, 8, '6-8', 42.86]
['Mike Dechaine', 'America', 1, 4, '1-4', 20.0, 2, 6, '2-6', 25.0, 3, 10, '3-10', 23.08]
['Dennis Hatch', 'America', 4, 3, '4-3', 57.14, 5, 7, '5-7', 41.67, 9, 10, '9-10', 47.37]
['Kim Davenport', 'America', 4, 0, '4-0', 100.0, 4, 2, '4-2', 66.67, 8, 2, '8-2', 80.0]
['Justin Bergman', 'America', 1, 4, '1-4', 20.0, 2, 2, '2-2', 50.0, 3, 6, '3-6', 33.33]
['James Rempe', 'America', 1, 2, '1-2', 33.33, 2, 4, '2-4', 33.33, 3, 6, '3-6', 33.33]
['Michael Coltrain', 'America', 1, 3, '1-3', 25.0, 3, 3, '3-3', 50.0, 4, 6, '4-6', 40.0]
['Shannon Daulton', 'America', 1, 1, '1-1', 50.0, 2, 1, '2-1', 66.67, 3, 2, '3-2', 60.0]
['Reed Pierce', 'America', 2, 0, '2-0', 100.0, 1, 2, '1-2', 33.33, 3, 2, '3-2', 60.0]
['Shawn Putnam', 'America', 0, 1, '0-1', 0.0, 2, 1, '2-1', 66.67, 2, 2, '2-2', 50.0]
['Tony Robles', 'America', 1, 3, '1-3', 25.0, 2, 3, '2-3', 40.0, 3, 6, '3-6', 33.33]
['John Schmidt', 'America', 1, 2, '1-2', 33.33, 0, 5, '0-5', 0.0, 1, 7, '1-7', 12.5]
['Skyler Woodward', 'America', 0, 2, '0-2', 0.0, 2, 1, '2-1', 66.67, 2, 3, '2-3', 40.0]
['Mike Davis', 'America', 1, 1, '1-1', 50.0, 1, 1, '1-1', 50.0, 2, 2, '2-2', 50.0]
['Justin Hall', 'America', 1, 0, '1-0', 100.0, 2, 1, '2-1', 66.67, 3, 1, '3-1', 75.0]
['Gabe Owen', 'America', 2, 0, '2-0', 100.0, 2, 1, '2-1', 66.67, 4, 1, '4-1', 80.0]
['Brandon Shuff', 'America', 0, 3, '0-3', 0.0, 1, 2, '1-2', 33.33, 1, 5, '1-5', 16.67]
['Óscar Domínguez', 'America', 0, 2, '0-2', 0.0, 2, 1, '2-1', 66.67, 2, 3, '2-3', 40.0]
['Ralf Souquet', 'Europe', 15, 10, '15-10', 60.0, 23, 15, '23-15', 60.53, 38, 25, '38-25', 60.32]
['Mika Immonen', 'Europe', 14, 13, '14-13', 51.85, 18, 17, '18-17', 51.43, 32, 30, '32-30', 51.61]
['Niels Feijen', 'Europe', 11, 8, '11-8', 57.89, 22, 9, '22-9', 70.97, 33, 17, '33-17', 66.0]
['Steve Davis', 'Europe', 6, 7, '6-7', 46.15, 7, 12, '7-12', 36.84, 13, 19, '13-19', 40.62]
['Oliver Ortmann', 'Europe', 3, 4, '3-4', 42.86, 4, 8, '4-8', 33.33, 7, 12, '7-12', 36.84]
['Darren Appleton', 'Europe', 9, 4, '9-4', 69.23, 8, 13, '8-13', 38.1, 17, 17, '17-17', 50.0]
['Nick van den Berg', 'Europe', 6, 8, '6-8', 42.86, 7, 11, '7-11', 38.89, 13, 19, '13-19', 40.62]
['Marcus Chamat', 'Europe', 4, 5, '4-5', 44.44, 7, 9, '7-9', 43.75, 11, 14, '11-14', 44.0]
['Karl Boyes', 'Europe', 4, 2, '4-2', 66.67, 10, 2, '10-2', 83.33, 14, 4, '14-4', 77.78]
['Steve Knight', 'Europe', 4, 3, '4-3', 57.14, 4, 7, '4-7', 36.36, 8, 10, '8-10', 44.44]
['Thomas Engert', 'Europe', 1, 5, '1-5', 16.67, 3, 5, '3-5', 37.5, 4, 10, '4-10', 28.57]
['Mark Gray', 'Europe', 0, 1, '0-1', 0.0, 2, 4, '2-4', 33.33, 2, 5, '2-5', 28.57]
['Thorsten Hohmann', 'Europe', 3, 3, '3-3', 50.0, 3, 5, '3-5', 37.5, 6, 8, '6-8', 42.86]
['Alex Lely', 'Europe', 0, 2, '0-2', 0.0, 2, 4, '2-4', 33.33, 2, 6, '2-6', 25.0]
['Albin Ouschan', 'Europe', 2, 0, '2-0', 100.0, 2, 1, '2-1', 66.67, 4, 1, '4-1', 80.0]
['Tony Drago', 'Europe', 4, 2, '4-2', 66.67, 0, 2, '0-2', 0.0, 4, 4, '4-4', 50.0]
['Nick Ekonomopoulos', 'Europe', 1, 1, '1-1', 50.0, 2, 1, '2-1', 66.67, 3, 2, '3-2', 60.0]
['Chris Melling', 'Europe', 5, 0, '5-0', 100.0, 1, 4, '1-4', 20.0, 6, 4, '6-4', 60.0]
['Daryl Peach', 'Europe', 0, 2, '0-2', 0.0, 1, 2, '1-2', 33.33, 1, 4, '1-4', 20.0]
['David Alcaide', 'Europe', 1, 0, '1-0', 100.0, 1, 1, '1-1', 50.0, 2, 1, '2-1', 66.67]
['Raj Hundal', 'Europe', 1, 0, '1-0', 100.0, 0, 3, '0-3', 0.0, 1, 3, '1-3', 25.0]
['Imran Majid', 'Europe', 1, 1, '1-1', 50.0, 1, 1, '1-1', 50.0, 2, 2, '2-2', 50.0]
['Fabio Petroni', 'Europe', 0, 2, '0-2', 0.0, 1, 2, '1-2', 33.33, 1, 4, '1-4', 20.0]
['Konstantin Stepanov', 'Europe', 0, 1, '0-1', 0.0, 2, 2, '2-2', 50.0, 2, 3, '2-3', 40.0]

In [170]:
stat_cols = ['player','team','s_wins','s_loss', 's_winloss', 's_pct','d_wins','d_loss', 'd_winloss', 'd_pct','c_wins','c_loss', 'c_winloss', 'c_pct']

In [258]:
#Most combined wins
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','c_winloss','c_pct','c_wins']].sort_values('c_wins',ascending=False).reset_index(drop=True)

                 player c_winloss  c_pct  c_wins
0         Johnny Archer     42-33  56.00      42
1          Ralf Souquet     38-25  60.32      38
2          Niels Feijen     33-17  66.00      33
3          Mika Immonen     32-30  51.61      32
4       Earl Strickland     31-21  59.62      31
5     Shane Van Boening     21-25  45.65      21
6         Rodney Morris     20-23  46.51      20
7           Corey Deuel     19-18  51.35      19
8       Darren Appleton     17-17  50.00      17
9          Jeremy Jones     16-16  50.00      16
10           Karl Boyes      14-4  77.78      14
11          Steve Davis     13-19  40.62      13
12    Nick van den Berg     13-19  40.62      13
13     Charlie Williams      12-9  57.14      12
14        Marcus Chamat     11-14  44.00      11
15         Dennis Hatch      9-10  47.37       9
16         Steve Knight      8-10  44.44       8
17        Kim Davenport       8-2  80.00       8
18       Oliver Ortmann      7-12  36.84       7
19        Chris Melling       6-4  60.00       6
20     Thorsten Hohmann       6-8  42.86       6
21          Nick Varner       6-8  42.86       6
22     Michael Coltrain       4-6  40.00       4
23            Gabe Owen       4-1  80.00       4
24           Tony Drago       4-4  50.00       4
25        Albin Ouschan       4-1  80.00       4
26        Thomas Engert      4-10  28.57       4
27        Mike Dechaine      3-10  23.08       3
28       Justin Bergman       3-6  33.33       3
29          James Rempe       3-6  33.33       3
30   Nick Ekonomopoulos       3-2  60.00       3
31          Justin Hall       3-1  75.00       3
32          Reed Pierce       3-2  60.00       3
33          Tony Robles       3-6  33.33       3
34      Shannon Daulton       3-2  60.00       3
35          Imran Majid       2-2  50.00       2
36        David Alcaide       2-1  66.67       2
37            Alex Lely       2-6  25.00       2
38      Óscar Domínguez       2-3  40.00       2
39            Mark Gray       2-5  28.57       2
40           Mike Davis       2-2  50.00       2
41      Skyler Woodward       2-3  40.00       2
42         Shawn Putnam       2-2  50.00       2
43  Konstantin Stepanov       2-3  40.00       2
44        Brandon Shuff       1-5  16.67       1
45          Daryl Peach       1-4  20.00       1
46         John Schmidt       1-7  12.50       1
47           Raj Hundal       1-3  25.00       1
48        Fabio Petroni       1-4  20.00       1

In [232]:
#Best combined win percentage
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','c_winloss','c_pct']].sort_values('c_pct',ascending=False).head(20).reset_index(drop=True)

                player c_winloss  c_pct
0        Albin Ouschan       4-1  80.00
1            Gabe Owen       4-1  80.00
2        Kim Davenport       8-2  80.00
3           Karl Boyes      14-4  77.78
4          Justin Hall       3-1  75.00
5        David Alcaide       2-1  66.67
6         Niels Feijen     33-17  66.00
7         Ralf Souquet     38-25  60.32
8        Chris Melling       6-4  60.00
9          Reed Pierce       3-2  60.00
10     Shannon Daulton       3-2  60.00
11  Nick Ekonomopoulos       3-2  60.00
12     Earl Strickland     31-21  59.62
13    Charlie Williams      12-9  57.14
14       Johnny Archer     42-33  56.00
15        Mika Immonen     32-30  51.61
16         Corey Deuel     19-18  51.35
17          Mike Davis       2-2  50.00
18     Darren Appleton     17-17  50.00
19        Shawn Putnam       2-2  50.00

In [248]:
#Most singles wins
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','s_winloss','s_wins']].sort_values('s_wins',ascending=False).head(11).reset_index(drop=True)

               player s_winloss  s_wins
0       Johnny Archer     15-13      15
1        Ralf Souquet     15-10      15
2        Mika Immonen     14-13      14
3     Earl Strickland      11-9      11
4        Niels Feijen      11-8      11
5   Shane Van Boening     10-14      10
6       Rodney Morris       9-8       9
7     Darren Appleton       9-4       9
8    Charlie Williams       6-2       6
9         Steve Davis       6-7       6
10       Jeremy Jones       6-7       6

In [256]:
#Best singles win percentage
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','s_winloss','s_pct']].sort_values('s_pct',ascending=False).head(20).reset_index(drop=True)

              player s_winloss   s_pct
0        Justin Hall       1-0  100.00
1      Chris Melling       5-0  100.00
2        Reed Pierce       2-0  100.00
3         Raj Hundal       1-0  100.00
4      Kim Davenport       4-0  100.00
5          Gabe Owen       2-0  100.00
6      David Alcaide       1-0  100.00
7      Albin Ouschan       2-0  100.00
8   Charlie Williams       6-2   75.00
9    Darren Appleton       9-4   69.23
10        Karl Boyes       4-2   66.67
11        Tony Drago       4-2   66.67
12      Ralf Souquet     15-10   60.00
13      Niels Feijen      11-8   57.89
14      Steve Knight       4-3   57.14
15      Dennis Hatch       4-3   57.14
16   Earl Strickland      11-9   55.00
17     Johnny Archer     15-13   53.57
18     Rodney Morris       9-8   52.94
19      Mika Immonen     14-13   51.85

In [224]:
#Most doubles wins
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','d_winloss','d_wins']].sort_values('d_wins',ascending=False).reset_index(drop=True).head(10)

              player d_winloss  d_wins
0      Johnny Archer     27-20      27
1       Ralf Souquet     23-15      23
2       Niels Feijen      22-9      22
3    Earl Strickland     20-12      20
4       Mika Immonen     18-17      18
5        Corey Deuel     13-12      13
6      Rodney Morris     11-15      11
7  Shane Van Boening     11-11      11
8       Jeremy Jones      10-9      10
9         Karl Boyes      10-2      10

In [257]:
#Best doubles win percentage
stats_df = pd.DataFrame(data=stat_l, columns = stat_cols)
stats_df[['player','d_winloss','d_pct']].sort_values('d_pct',ascending=False).head(20).reset_index(drop=True)

                player d_winloss  d_pct
0           Karl Boyes      10-2  83.33
1         Niels Feijen      22-9  70.97
2      Óscar Domínguez       2-1  66.67
3      Shannon Daulton       2-1  66.67
4   Nick Ekonomopoulos       2-1  66.67
5        Albin Ouschan       2-1  66.67
6            Gabe Owen       2-1  66.67
7          Justin Hall       2-1  66.67
8        Kim Davenport       4-2  66.67
9      Skyler Woodward       2-1  66.67
10        Shawn Putnam       2-1  66.67
11     Earl Strickland     20-12  62.50
12        Ralf Souquet     23-15  60.53
13       Johnny Archer     27-20  57.45
14         Nick Varner       5-4  55.56
15        Jeremy Jones      10-9  52.63
16         Corey Deuel     13-12  52.00
17        Mika Immonen     18-17  51.43
18    Michael Coltrain       3-3  50.00
19         Imran Majid       1-1  50.00

In [176]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [263]:
playerinfo('Niels Feijen','u')

['Niels Feijen', 'u', 11, 8, '11-8', 57.89, 22, 9, '22-9', 70.97, 33, 17, '33-17', 66.0]

,Format,European_player,European_score,American_score,American_player,Europe_won
0,Doubles,Niels Feijen Mika Immonen,5,3,Nick Varner Johnny Archer,True
4,Doubles,Niels Feijen Mika Immonen,4,5,Nick Varner Johnny Archer,False
10,Singles,Niels Feijen,2,5,Earl Strickland,False
0,Doubles,Steve Davis Niels Feijen,5,4,Charlie Williams Tony Robles,True
4,Doubles,Steve Davis Niels Feijen,5,3,Johnny Archer Gabe Owen,True
7,Singles,Niels Feijen,1,5,Charlie Williams,False
10,Doubles,Steve Davis Niels Feijen,3,5,Charlie Williams Tony Robles,False
16,Singles,Niels Feijen,5,2,Johnny Archer,True
0,Doubles,Thorsten Hohmann Niels Feijen,5,1,Johnny Archer Jeremy Jones,True
3,Singles,Niels Feijen,3,5,Charlie Williams,False
5,Doubles,Thorsten Hohmann Niels Feijen,4,5,Charlie Williams Shaun Putnam,False
10,Doubles,Niels Feijen Alex Lely,5,3,Charlie Williams Shaun Putnam,True
1,Doubles,Niels Feijen Ralf Souquet,6,4,Johnny Archer Rodney Morris,True
4,Singles,Niels Feijen,1,6,Rodney Morris,False
7,Doubles,Konstantin Stepanov Niels Feijen,6,1,Corey Deuel Johnny Archer,True
10,Doubles,Konstantin Stepanov Niels Feijen,6,2,Corey Deuel Johnny Archer,True
13,Singles,Niels Feijen,6,4,Rodney Morris,True
1,Doubles,Niels Feijen Ralf Souquet,5,3,Shane Van Boening Rodney Morris,True
4,Doubles,Niels Feijen Ralf Souquet,5,3,Shane Van Boening Rodney Morris,True
8,Doubles,Niels Feijen Ralf Souquet,5,1,Earl Strickland Rodney Morris,True
11,Singles,Niels Feijen,3,5,Rodney Morris,False
14,Doubles,Niels Feijen Ralf Souquet,5,2,Rodney Morris Jeremy Jones,True
1,Doubles,Niels Feijen Darren Appleton,5,6,Johnny Archer Dennis Hatch,False
5,Doubles,Ralf Souquet Niels Feijen,2,6,Shane Van Boening Johnny Archer,False
9,Doubles,Niels Feijen Thorsten Hohmann,6,1,Dennis Hatch Corey Deuel,True
11,Singles,Niels Feijen,4,6,Dennis Hatch,False
15,Singles,Niels Feijen,0,6,Dennis Hatch,False
2,Singles,Niels Feijen,6,0,Rodney Morris,True
5,Doubles,Nick van den Berg Niels Feijen,5,6,Shane Van Boening Johnny Archer,False
10,Doubles,Darren Appleton Niels Feijen,6,3,Shawn Putnam Mike Dechaine,True
12,Doubles,Ralf Souquet Niels Feijen,6,2,Johnny Archer Rodney Morris,True
17,Singles,Niels Feijen,6,4,Rodney Morris,True
2,Singles,Niels Feijen,5,0,Mike Dechaine,True
7,Doubles,Niels Feijen Nick van den Berg,5,2,Dennis Hatch Brandon Shuff,True
9,Doubles,Darren Appleton Niels Feijen,4,5,Shane Van Boening Johnny Archer,False
12,Doubles,Nick Ekonomopoulos Niels Feijen,5,4,Dennis Hatch Mike Dechaine,True
16,Singles,Niels Feijen,1,5,Johnny Archer,False
3,Doubles,Niels Feijen Ralf Souquet,6,3,Johnny Archer Dennis Hatch,True
5,Doubles,Karl Boyes Niels Feijen,6,4,Johnny Archer Rodney Morris,True
8,Singles,Niels Feijen,6,0,Johnny Archer,True
12,Doubles,Mika Immonen Niels Feijen,6,4,Dennis Hatch Rodney Morris,True
3,Doubles,Niels Feijen & Nikos Ekonomopoulos,5,1,Shane Van Boening & Justin Bergman,True
5,Doubles,Niels Feijen & Mark Gray,2,5,Justin Hall & Justin Bergman,False
8,Singles,Niels Feijen,5,3,Justin Bergman,True
13,Singles,Niels Feijen,5,2,Justin Bergman,True
2,Singles,Niels Feijen,5,2,Justin Bergman,True
5,Doubles,Niels Feijen Nick van den Berg,3,5,Justin Bergman Skyler Woodward,False
10,Doubles,Niels Feijen Albin Ouschan,5,1,Justin Bergman Corey Deuel,True
13,Singles,Niels Feijen,5,4,Shane Van Boening,True
15,Singles,Niels Feijen,5,4,Justin Bergman,True

In [265]:
playerinfo('Mike Dechaine','am')

['Mike Dechaine', 'am', 1, 4, '1-4', 20.0, 2, 6, '2-6', 25.0, 3, 10, '3-10', 23.08]

,Format,European_player,European_score,American_score,American_player,Europe_won
3,Doubles,Darren Appleton Ralf Souquet,6,4,Shane Van Boening Mike Dechaine,True
6,Singles,Ralf Souquet,1,6,Mike Dechaine,False
10,Doubles,Darren Appleton Niels Feijen,6,3,Shawn Putnam Mike Dechaine,True
14,Singles,Chris Melling,6,2,Mike Dechaine,True
2,Singles,Niels Feijen,5,0,Mike Dechaine,True
5,Doubles,Darren Appleton Chris Melling,4,5,Johnny Archer Mike Dechaine,False
10,Doubles,Nick van den Berg Nick Ekonomopoulos,5,4,Mike Dechaine Brandon Shuff,True
12,Doubles,Nick Ekonomopoulos Niels Feijen,5,4,Dennis Hatch Mike Dechaine,True
19,Singles,Nick van den Berg,5,2,Mike Dechaine,True
1,Doubles,Karl Boyes Nick van den Berg,5,4,Corey Deuel Mike Dechaine,True
6,Singles,Albin Ouschan,5,3,Mike Dechaine,True
9,Doubles,Darren Appleton Nick van den Berg,4,5,Shane Van Boening Mike Dechaine,False
12,Doubles,Karl Boyes Albin Ouschan,5,2,Mike Dechaine Skyler Woodward,True