In [1]:
import pandas as pd

In [2]:
import sqlite3

In [3]:
sql = 'select * from results'

con = sqlite3.connect('players.db')

df = pd.read_sql(sql,con,index_col=['Year','Match'])

In [4]:
df.drop('index',axis=1,inplace=True)

In [5]:
df = df.reset_index()

In [6]:
df.columns = map(str.lower, df.columns)

In [7]:
df

,year,match,format,european_player,european_score,american_score,american_player,europe_won
0,1994,0,Singles,Tom Storm,2,0,Bobby Hunter,1
1,1994,1,Singles,Oliver Ortmann,2,0,Mark Wilson,1
2,1994,2,Singles,Lee Tucker,1,2,Lou Butera,0
3,1994,3,Singles,Allison Fisher,0,2,Vivian Villarreal,0
4,1994,4,Singles,Steve Davis,2,1,Mike Gulyassy,1
...,...,...,...,...,...,...,...,...
506,2019,14,Doubles,"Niels Feijen, Jayson Shaw",5,4,"Justin Bergman, Billy Thorpe",1
507,2019,15,Singles,Jayson Shaw,3,5,Billy Thorpe,0
508,2019,16,Singles,Eklent Kaçi,5,1,Tyler Styer,1
509,2019,17,Singles,Alexander Kazakis,3,5,Shane Van Boening,0
510,2019,18,Singles,Joshua Filler,3,5,Skyler Woodward,0

In [54]:
df[df['year']=='2019']

,year,match,format,european_player,european_score,american_score,american_player,europe_won
492,2019,0,Teams,Team Europe,1,5,Team USA,0
493,2019,1,Doubles,"Eklent Kaçi, Niels Feijen",4,5,"Shane Van Boening, Tyler Styer",0
494,2019,2,Singles,Joshua Filler,5,0,Billy Thorpe,1
495,2019,3,Doubles,"Alexander Kazakis, Jayson Shaw",5,1,"Skyler Woodward, Justin Bergman",1
496,2019,4,Singles,Jayson Shaw,5,3,Justin Bergman,1
497,2019,5,Singles,Joshua Filler,5,1,Shane Van Boening,1
498,2019,6,Doubles,"Joshua Filler, Jayson Shaw",1,5,"Shane Van Boening, Justin Bergman",0
499,2019,7,Singles,Eklent Kaçi,5,1,Tyler Styer,1
500,2019,8,Doubles,"Niels Feijen, Alexander Kazakis",1,5,"Billy Thorpe, Skyler Woodward",0
501,2019,9,Singles,Alexander Kazakis,1,5,Shane Van Boening,0
502,2019,10,Doubles,"Joshua Filler, Eklent Kaçi",1,5,"Shane Van Boening, Skyler Woodward",0
503,2019,11,Singles,Niels Feijen,3,5,Skyler Woodward,0
504,2019,12,Doubles,"Eklent Kaçi, Alexander Kazakis",4,5,"Skyler Woodward, Tyler Styer",0
505,2019,13,Singles,Joshua Filler,5,0,Shane Van Boening,1
506,2019,14,Doubles,"Niels Feijen, Jayson Shaw",5,4,"Justin Bergman, Billy Thorpe",1
507,2019,15,Singles,Jayson Shaw,3,5,Billy Thorpe,0
508,2019,16,Singles,Eklent Kaçi,5,1,Tyler Styer,1
509,2019,17,Singles,Alexander Kazakis,3,5,Shane Van Boening,0
510,2019,18,Singles,Joshua Filler,3,5,Skyler Woodward,0

In [55]:
df['year']=pd.to_numeric(df['year'])

In [56]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.express as px

import pandas as pd

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(id='graph-with-slider'),
    dcc.Slider(
        id='year-slider',
        min=df['year'].min(),
        max=df['year'].max(),
        value=df['year'].min(),
        marks={str(year): str(year) for year in df['year'].unique()},
        step=None
    )
])


@app.callback(
    Output('graph-with-slider', 'figure'),
    [Input('year-slider', 'value')])
def update_figure(selected_year):
    filtered_df = df[df.year == selected_year]

    fig = px.scatter(filtered_df,x='american_score',y='european_score')

    fig.update_layout(transition_duration=500)

    return fig


if __name__ == '__main__':
    app.run_server(debug=True,use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 Warning: This is a development server. Do not use app.run_server
 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 in production, use a production WSGI server like gunicorn instead.

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

In [11]:
df[df['american_player']=='Shane Van Boening'].year.drop_duplicates()

288    2007
314    2008
323    2009
345    2010
362    2011
382    2012
398    2013
413    2014
429    2015
447    2016
461    2017
476    2018
497    2019
Name: year, dtype: object