In [5]:
import pandas as pd

In [6]:
import sqlite3

In [7]:
con = sqlite3.connect('../players.db')

In [8]:
sql = 'select * from results'

In [11]:
df = pd.read_sql(sql,con,index_col=['Year','Match'])

In [15]:
df.drop('index',axis=1,inplace=True)

In [16]:
df

             Format    European_player European_score American_score  \
Year Match
1994 0      Singles          Tom Storm              2              0
     1      Singles     Oliver Ortmann              2              0
     2      Singles         Lee Tucker              1              2
     3      Singles     Allison Fisher              0              2
     4      Singles        Steve Davis              2              1
...             ...                ...            ...            ...
2018 15     Singles      Albin Ouschan              4              5
     16     Singles        Jayson Shaw              5              3
     17     Singles       Niels Feijen              5              1
     18     Singles        Eklent Kaci              5              2
     19     Singles  Alexander Kazakis              3              5

              American_player  Europe_won
Year Match
1994 0           Bobby Hunter           1
     1            Mark Wilson           1
     2             Lou Butera           0
     3      Vivian Villarreal           0
     4          Mike Gulyassy           1
...                       ...         ...
2018 15       Skyler Woodward           0
     16           Tyler Styer           1
     17           Corey Deuel           1
     18          Billy Thorpe           1
     19     Shane Van Boening           0

[492 rows x 6 columns]

In [30]:
so = df[df['American_score']=='0']

In [32]:
len(so['Format'])

38

In [34]:
len(df['Format'])

492

In [36]:
38/492*100

7.723577235772358

7.72 percent of matches have been whitewash

In [33]:
so

             Format                   European_player European_score  \
Year Match
1994 0      Singles                         Tom Storm              2
     1      Singles                    Oliver Ortmann              2
     5      Singles                         Tom Storm              2
     7      Singles                        Lee Tucker              2
     9      Singles                      Ralf Souquet              2
     12     Singles                       Jimmy White              2
     14     Singles                      Ralf Souquet              2
     23     Singles                    Oliver Ortmann              2
     26     Singles                        Lee Tucker              2
1995 0      Singles                       Steve Davis              2
     4      Singles                    Oliver Ortmann              2
     10     Doubles          Oliver Ortmann Tom Storm              2
     12     Singles                       Daryl Peach              2
     19     Singles                    Oliver Ortmann              2
     20     Singles                       Daryl Peach              2
     22     Singles                    Oliver Ortmann              2
     24     Singles                    Oliver Ortmann              2
     30     Singles                       Jimmy White              1
1996 2      Singles                      Mika Immonen              2
     4      Singles                      Ralf Souquet              2
     8      Doubles      Mika Immonen Vincent Facquet              2
     11     Doubles       Ralf Souquet Oliver Ortmann              2
     15     Singles                      Ralf Souquet              2
     25     Singles                      Ralf Souquet              1
1997 10     Doubles     Steve Davis Ronnie O'Sullivan              2
     14     Singles                       Steve Davis              2
2000 17     Singles                       Steve Davis              5
2002 5      Doubles     Steve Davis Nick van den Berg              5
     9      Doubles        Marcus Chamat Mika Immonen              5
2003 11     Singles                       Steve Davis              5
2004 3      Doubles        Mika Immonen Marcus Chamat              5
2007 5      Doubles          Daryl Peach Ralf Souquet              6
2008 7      Singles                      Mika Immonen              5
2011 2      Singles                      Niels Feijen              6
2012 2      Singles                      Niels Feijen              5
     14     Singles                   Darren Appleton              5
2013 8      Singles                      Niels Feijen              6
2017 9      Doubles  Joshua Filler, Nick van den Berg              5

           American_score                    American_player  Europe_won
Year Match
1994 0                  0                       Bobby Hunter           1
     1                  0                        Mark Wilson           1
     5                  0                         Lou Butera           1
     7                  0                        Mark Wilson           1
     9                  0                        Dallas West           1
     12                 0                         Paul Gerni           1
     14                 0                       Bobby Hunter           1
     23                 0                       Bobby Hunter           1
     26                 0                         Paul Gerni           1
1995 0                  0                        Mike Massey           1
     4                  0                         Lou Butera           1
     10                 0          Mike Gulyassy John DiToro           1
     12                 0                        Mark Wilson           1
     19                 0                        Dallas West           1
     20                 0                        Mike Massey           1
     22                 0                        Mark Wilson           1
     24                 0                       Bobby Hunter           1
     30                 0                         Lou Butera           1
1996 2                  0                      Roger Griffis           1
     4                  0                         C.J. Wiley           1
     8                  0          Allen Hopkins Mike Massey           1
     11                 0     Danny Harriman Shannon Daulton           1
     15                 0                      Roger Griffis           1
     25                 0                    Earl Strickland           1
1997 10                 0          Johnny Archer Reed Pierce           1
     14                 0                      Kim Davenport           1
2000 17                 0                   Michael Coltrain           1
2002 5                  0       Earl Strickland Jeremy Jones           1
     9                  0       Corey Deuel Charlie Williams           1
2003 11                 0                    Earl Strickland           1
2004 3                  0       Charlie Williams Tony Robles           1
2007 5                  0  Earl Strickland Shane Van Boening           1
2008 7                  0                    Earl Strickland           1
2011 2                  0                      Rodney Morris           1
2012 2                  0                      Mike Dechaine           1
     14                 0                  Shane Van Boening           1
2013 8                  0                      Johnny Archer           1
2017 9                  0    Shane Van Boening, Billy Thorpe           1

In [24]:
df[df['American_score']=='0']['European_player'].value_counts()

Oliver Ortmann                      6
Ralf Souquet                        5
Steve Davis                         4
Niels Feijen                        3
Daryl Peach                         2
Mika Immonen                        2
Tom Storm                           2
Jimmy White                         2
Lee Tucker                          2
Darren Appleton                     1
Steve Davis Nick van den Berg       1
Steve Davis Ronnie O'Sullivan       1
Mika Immonen Vincent Facquet        1
Joshua Filler, Nick van den Berg    1
Oliver Ortmann Tom Storm            1
Marcus Chamat Mika Immonen          1
Ralf Souquet Oliver Ortmann         1
Mika Immonen Marcus Chamat          1
Daryl Peach Ralf Souquet            1
Name: European_player, dtype: int64

In [25]:
df[df['European_score']=='0']['American_player'].value_counts()

Shannon Daulton                   4
C.J. Wiley                        3
Vivian Villarreal                 2
Roger Griffis                     2
Nick Varner                       2
Earl Strickland                   2
Bobby Hunter                      2
Dallas West Vivian Villarreal     1
Jeanette Lee                      1
Earl Strickland C.J. Wiley        1
Mike Massey                       1
Mark Wilson Lou Butera            1
John DiToro                       1
Mark Wilson                       1
Dallas West Mike Massey           1
Earl Strickland Rodney Morris     1
Mike Gulyassy                     1
Lou Butera                        1
Danny Harriman                    1
Johnny Archer                     1
James Rempe                       1
Dallas West Mike Gulyassy         1
Bobby Hunter Jeanette Lee         1
Johnny Archer Shannon Daulton     1
Reed Pierce                       1
Dennis Hatch                      1
Dallas West                       1
Lou Butera John DiToro            1
Jeanette Lee Vivian Villarreal    1
Shane Van Boening                 1
Name: American_player, dtype: int64

             Format                                    European_player  \
Year Match
2015 0        Teams  Darren Appleton, Karl Boyes, Niels Feijen, Alb...
     3      Doubles                      Darren Appleton Albin Ouschan
     5      Doubles                     Niels Feijen Nick van den Berg
     8      Singles                                         Karl Boyes
     12     Doubles                           Karl Boyes Albin Ouschan
     17     Singles                                      Albin Ouschan
2016 0        Teams  Darren Appleton, Niels Feijen, Albin Ouschan, ...
     3      Doubles                        Jayson Shaw Darren Appleton
     5      Doubles                             Niels Feijen Mark Gray
     10     Doubles                          Jayson Shaw Albin Ouschan
     11     Singles                                      Albin Ouschan
2017 0        Teams  Nick van den Berg, Jayson Shaw, David Alcaide,...
     1      Doubles                         David Alcaide, Jayson Shaw
     7      Doubles                         Joshua Filler, Jayson Shaw
     8      Singles                                      David Alcaide
     12     Doubles                        David Alcaide, Ralf Souquet
2018 0        Teams  Albin Ouschan, Jayson Shaw, Niels Feijen, Ekle...
     1      Doubles                         Albin Ouschan, Jayson Shaw
     6      Doubles                    Niels Feijen, Alexander Kazakis
     10     Doubles                        Niels Feijen, Albin Ouschan
     11     Singles                                  Alexander Kazakis
     13     Singles                                        Jayson Shaw
     15     Singles                                      Albin Ouschan

           European_score American_score  \
Year Match
2015 0                  4              5
     3                  1              5
     5                  3              5
     8                  5              3
     12                 5              2
     17                 5              4
2016 0                  5              2
     3                  1              5
     5                  5              2
     10                 5              3
     11                 5              4
2017 0                  5              3
     1                  5              3
     7                  5              1
     8                  5              1
     12                 5              2
2018 0                  5              4
     1                  5              1
     6                  3              5
     10                 4              5
     11                 3              5
     13                 4              5
     15                 4              5

                                              American_player  Europe_won
Year Match
2015 0      Shane Van Boening, Corey Deuel, Skyler Woodwar...           0
     3                      Shane Van Boening Skyler Woodward           0
     5                         Justin Bergman Skyler Woodward           0
     8                                        Skyler Woodward           1
     12                         Mike Dechaine Skyler Woodward           1
     17                                       Skyler Woodward           1
2016 0      Rodney Morris, Justin Bergman, Skyler Woodward...           1
     3                         Skyler Woodward Justin Bergman           0
     5                      Shane Van Boening Skyler Woodward           1
     10                         Rodney Morris Skyler Woodward           1
     11                                       Skyler Woodward           1
2017 0      Dennis Hatch, Billy Thorpe, Shane Van Boening,...           1
     1                          Billy Thorpe, Skyler Woodward           1
     7                     Shane Van Boening, Skyler Woodward           1
     8                                        Skyler Woodward           1
     12                      Skyler Woodward, Oscar Dominguez           1
2018 0      Billy Thorpe, Skyler Woodward, Tyler Styer, Sh...           1
     1                          Billy Thorpe, Skyler Woodward           1
     6                     Skyler Woodward, Shane Van Boening           0
     10                          Skyler Woodward, Tyler Styer           0
     11                                       Skyler Woodward           0
     13                                       Skyler Woodward           0
     15                                       Skyler Woodward           0