In [1]:
import sqlite3

In [2]:
import pandas as pd

In [3]:
con=sqlite3.connect('../players.db')

In [4]:
sql='select * from players'

In [5]:
df = pd.read_sql(sql,con)

In [7]:
df.head()

,Name,Location,Team,Appearances,Win-loss-tie,Wins,Losses,Pct
0,Johnny Archer,Georgia,America,17,9-7-1,9,7,52.94
1,Earl Strickland,North Carolina,America,14,9-4-1,9,4,64.29
2,Rodney Morris,California,America,10,3-6-1,3,6,30.00
3,Shane Van Boening,South Dakota,America,10,1-9-0,1,9,10.00
4,Corey Deuel,California,America,9,3-5-1,3,5,33.33

In [9]:
df.sort_values('Appearances',ascending=False)

,Name,Location,Team,Appearances,Win-loss-tie,Wins,Losses,Pct
0,Johnny Archer,Georgia,America,17,9-7-1,9,7,52.94
40,Ralf Souquet,Germany,Europe,16,6-9-1,6,9,37.50
41,Mika Immonen,Finland,Europe,15,4-10-1,4,10,26.67
1,Earl Strickland,North Carolina,America,14,9-4-1,9,4,64.29
42,Niels Feijen,Netherlands,Europe,12,8-4-0,8,4,66.67
43,Steve Davis,England,Europe,11,2-9-0,2,9,18.18
2,Rodney Morris,California,America,10,3-6-1,3,6,30.00
3,Shane Van Boening,South Dakota,America,10,1-9-0,1,9,10.00
4,Corey Deuel,California,America,9,3-5-1,3,5,33.33
44,Oliver Ortmann,Germany,Europe,8,2-6-0,2,6,25.00
45,Darren Appleton,England,Europe,8,7-1-0,7,1,87.50
46,Nick van den Berg,Netherlands,Europe,7,5-1-1,5,1,71.43
5,Jeremy Jones,Texas,America,7,5-2-0,5,2,71.43
47,Marcus Chamat,Sweden,Europe,6,1-5-0,1,5,16.67
6,Charlie Williams,South Korea,America,5,4-1-0,4,1,80.00
49,Steve Knight,England,Europe,4,0-4-0,0,4,0.00
7,Nick Varner,Kentucky,America,4,3-1-0,3,1,75.00
8,Mike Dechaine,Maine,America,4,0-4-0,0,4,0.00
9,Dennis Hatch,Michigan,America,4,1-3-0,1,3,25.00
48,Karl Boyes,England,Europe,4,4-0-0,4,0,100.00
52,Thorsten Hohmann,Germany,Europe,3,0-3-0,0,3,0.00
50,Thomas Engert,Germany,Europe,3,0-2-1,0,2,0.00
51,Mark Gray,England,Europe,3,3-0-0,3,0,100.00
12,James Rempe,Pennsylvania,America,3,3-0-0,3,0,100.00
11,Justin Bergman,Illinois,America,3,0-3-0,0,3,0.00
10,Kim Davenport,Oklahoma,America,3,3-0-0,3,0,100.00
53,Alex Lely,Netherlands,Europe,2,0-2-0,0,2,0.00
35,Bobby Hunter,Michigan,America,2,1-1-0,1,1,50.00
55,Tony Drago,Malta,Europe,2,2-0-0,2,0,100.00
60,Tom Storm,Sweden,Europe,2,1-1-0,1,1,50.00
...,...,...,...,...,...,...,...,...
74,Konstantin Stepanov,Russia,Europe,1,1-0-0,1,0,100.00
73,Franziska Stark,Germany,Europe,1,0-1-0,0,1,0.00
64,Vincent Facquet,France,Europe,1,0-1-0,0,1,0.00
65,Allison Fisher,England,Europe,1,0-1-0,0,1,0.00
72,Jayson Shaw,Scotland,Europe,1,1-0-0,1,0,100.00
71,Andy Richardson,England,Europe,1,0-1-0,0,1,0.00
70,Fabio Petroni,Italy,Europe,1,0-1-0,0,1,0.00
68,Lee Kendall,England,Europe,1,1-0-0,1,0,100.00
67,Raj Hundal,England,Europe,1,0-1-0,0,1,0.00
66,Alex Higgins,Northern Ireland,Europe,1,1-0-0,1,0,100.00
62,David Alcaide,Spain,Europe,1,0-0-1,0,0,0.00
63,Tommy Donlon,Ireland,Europe,1,0-1-0,0,1,0.00
69,Imran Majid,England,Europe,1,0-0-1,0,0,0.00
38,Brandon Shuff,Virginia,America,1,0-1-0,0,1,0.00
56,Nick Ekonomopoulos,Greece,Europe,1,1-0-0,1,0,100.00
39,Vivian Villarreal,Texas,America,1,1-0-0,1,0,100.00
37,Gabe Owen,Kansas,America,1,1-0-0,1,0,100.00
36,Jeanette Lee,New York,America,1,1-0-0,1,0,100.00
34,Allen Hopkins,New Jersey,America,1,1-0-0,1,0,100.00
33,Danny Harriman,Maryland,America,1,1-0-0,1,0,100.00
32,Justin Hall,Illinois,America,1,0-1-0,0,1,0.00
31,Roger Griffis,Texas,America,1,1-0-0,1,0,100.00
30,Paul Gerni,New Jersey,America,1,1-0-0,1,0,100.00
29,Oscar Dominguez,California,America,1,1-0-0,1,0,100.00
28,John DiToro,Florida,America,1,0-1-0,0,1,0.00
27,Mike Davis,North Carolina,America,1,0-0-1,0,0,0.00
26,C.J. Wiley,Texas,America,1,1-0-0,1,0,100.00
21,Shawn Putnam,Pennsylvania,America,1,0-1-0,0,1,0.00
18,Robert Hunter,Michigan,America,1,0-1-0,0,1,0.00
75,Lee Tucker,England,Europe,1,0-1-0,0,1,0.00