In [2]:
import pandas as pd
import pickle

In [3]:
import os

In [4]:
parent = os.path.abspath('..')
path = os.path.join(parent,'pkl/allyears_clean')
df = pickle.load(open(path,'rb'))

Let see how the teams matches went each year according to who was home and who was away

In [5]:
yearly = pd.read_csv(os.path.join(parent,'yearly.csv'),'rb',engine='python',delimiter=',')

In [25]:
yearly

,Year,Venue,Victors,Score,Losers,MVP,Mvp
0,1994,"Romford, London, England",USA,16–12,Europe,Mika Immonen,Mika Immonen
1,1995,"Basildon, Essex, England",Europe,16–15,USA,Mika Immonen,Mika Immonen
2,1996,"Dagenham, London, England",USA,15–13,Europe,Mika Immonen,Mika Immonen
3,1997,"Bethnal Green, London, England",USA,13–8,Europe,Mika Immonen,Mika Immonen
4,1998,"Bethnal Green, London, England",USA,13–9,Europe,Mika Immonen,Mika Immonen
5,1999,"Bethnal Green, London, England",USA,12–7,Europe,Mika Immonen,Mika Immonen
6,2000,"Bethnal Green, London, England",USA,12–9,Europe,Mika Immonen,Mika Immonen
7,2001,"Bethnal Green, London, England",USA,12–1,Europe,Mika Immonen,Mika Immonen
8,2002,"Bethnal Green, London, England",Europe,12–9,USA,Mika Immonen,Mika Immonen
9,2003,"Las Vegas, Nevada, USA",USA,11–9,Europe,Mika Immonen,Mika Immonen
10,2004,"Egmond aan Zee, Netherlands",USA,12–9,Europe,Rodney Morris,Rodney Morris
11,2005,"Las Vegas, Nevada, USA",USA,11–6,Europe,Earl Strickland,Earl Strickland
12,2006,"Rotterdam, Netherlands",Tied,12–12,Tied,Corey Deuel,Corey Deuel
13,2007,"Las Vegas, Nevada, USA",Europe,11–8,USA,Tony Drago,Tony Drago
14,2008,"St. Julian's, Malta",Europe,11–5,USA,Mika Immonen,Mika Immonen
15,2009,"Las Vegas, Nevada, USA",USA,11–7,Europe,Dennis Hatch,Dennis Hatch
16,2010,"Bethnal Green, London, England",Europe,11–8,USA,Darren Appleton,Darren Appleton
17,2011,"Las Vegas, Nevada, USA",Europe,11–7,USA,Niels Feijen,Niels Feijen
18,2012,"Bethnal Green, London, England",Europe,11–9,USA,Chris Melling,Chris Melling
19,2013,"Las Vegas, Nevada, USA",Europe,11–2,USA,Niels Feijen,Niels Feijen
20,2014,"Tower Circus, Blackpool, England",Europe,11–5,USA,Niels Feijen,Niels Feijen
21,2015,"Las Vegas, Nevada, USA",Europe,11–7,USA,Niels Feijen,Niels Feijen
22,2016,"Alexandra Palace, London, England",Europe,11–3,USA,Albin Ouschan,Albin Ouschan

In [12]:
yearly.fillna(method='bfill',inplace=True)

In [24]:
yearly['MVP']=yearly['MVP'].map(lambda x: ' '.join(x.split()[-2:]))

In [36]:
def clean(x):
    try:
        x.str.split()
        " ".join(item[-2:])
    except:
        pass

In [26]:
yearly = yearly.drop('Mvp',axis=1)

In [40]:
import numpy as np

In [41]:
yearly.ix[0:8,'MVP']=np.nan

In [42]:
yearly

,Year,Venue,Victors,Score,Losers,MVP
0,1994,"Romford, London, England",USA,16–12,Europe,NaN
1,1995,"Basildon, Essex, England",Europe,16–15,USA,NaN
2,1996,"Dagenham, London, England",USA,15–13,Europe,NaN
3,1997,"Bethnal Green, London, England",USA,13–8,Europe,NaN
4,1998,"Bethnal Green, London, England",USA,13–9,Europe,NaN
5,1999,"Bethnal Green, London, England",USA,12–7,Europe,NaN
6,2000,"Bethnal Green, London, England",USA,12–9,Europe,NaN
7,2001,"Bethnal Green, London, England",USA,12–1,Europe,NaN
8,2002,"Bethnal Green, London, England",Europe,12–9,USA,NaN
9,2003,"Las Vegas, Nevada, USA",USA,11–9,Europe,Mika Immonen
10,2004,"Egmond aan Zee, Netherlands",USA,12–9,Europe,Rodney Morris
11,2005,"Las Vegas, Nevada, USA",USA,11–6,Europe,Earl Strickland
12,2006,"Rotterdam, Netherlands",Tied,12–12,Tied,Corey Deuel
13,2007,"Las Vegas, Nevada, USA",Europe,11–8,USA,Tony Drago
14,2008,"St. Julian's, Malta",Europe,11–5,USA,Mika Immonen
15,2009,"Las Vegas, Nevada, USA",USA,11–7,Europe,Dennis Hatch
16,2010,"Bethnal Green, London, England",Europe,11–8,USA,Darren Appleton
17,2011,"Las Vegas, Nevada, USA",Europe,11–7,USA,Niels Feijen
18,2012,"Bethnal Green, London, England",Europe,11–9,USA,Chris Melling
19,2013,"Las Vegas, Nevada, USA",Europe,11–2,USA,Niels Feijen
20,2014,"Tower Circus, Blackpool, England",Europe,11–5,USA,Niels Feijen
21,2015,"Las Vegas, Nevada, USA",Europe,11–7,USA,Niels Feijen
22,2016,"Alexandra Palace, London, England",Europe,11–3,USA,Albin Ouschan

In [43]:
import sqlalchemy

In [45]:
path = os.path.join(parent,'players.db')
engine = sqlalchemy.create_engine('sqlite:///{}'.format(path))

In [46]:
conn = engine.connect()

In [49]:
yearly.to_sql('yearly',conn)