Update player database

In [1]:
import sqlite3

In [2]:
con = sqlite3.connect('../players.db')

In [3]:
import pandas as pd

In [6]:
# df = pd.read_sql('select * from results',con)
# df.set_index(['Year','Match'],inplace=True)
# eu = list(df[df.Format=='Singles']['European_player'])
# am = list(df[df.Format=='Singles']['American_player'])
# am=list(set(am))
# eu=list(set(eu))

Switch to diff method of manual scrape wikipedia for players

In [144]:
am = pd.read_csv('../am.csv')

In [145]:
eu = pd.read_csv('../eu.csv')

In [146]:
l=[am,eu]

In [147]:
for i in l:
    i.columns=['P', 'NP', 'Name', 'Location']

In [148]:
f = pd.concat([am,eu])

In [149]:
f

     P  NP                 Name           Location
0   17   0        Johnny Archer            Georgia
1   14   0      Earl Strickland     North Carolina
2   11   0    Shane Van Boening       South Dakota
3   10   0        Rodney Morris         California
4    9   0          Corey Deuel         California
5    7   0         Jeremy Jones              Texas
6    5   1     Charlie Williams       South Korea1
7    5   0         Dennis Hatch           New York
8    4   4          Nick Varner           Kentucky
9    4   0        Mike Dechaine              Maine
10   3   1        Kim Davenport           Oklahoma
11   3   0       Justin Bergman           Illinois
12   3   0          James Rempe       Pennsylvania
13   3   0      Skyler Woodward           Kentucky
14   2   3          Mark Wilson           Missouri
15   2   0           Lou Butera       Pennsylvania
16   2   0     Michael Coltrain     North Carolina
17   2   0      Shannon Daulton           Kentucky
18   2   0        Mike Gulyassy               Ohio
19   2   0         Bobby Hunter           Michigan
20   2   0          Mike Massey          Tennessee
21   2   0          Reed Pierce        Mississippi
22   2   0         Shawn Putnam       Pennsylvania
23   2   0          Tony Robles           New York
24   2   0         John Schmidt         California
25   2   0          Dallas West           Illinois
26   2   0      Óscar Domínguez         California
27   1   1           C.J. Wiley              Texas
28   1   0           Mike Davis     North Carolina
29   1   0          John DiToro            Florida
30   1   0           Paul Gerni      New Jersey[3]
31   1   0        Roger Griffis              Texas
32   1   0          Justin Hall           Illinois
33   1   0       Danny Harriman           Maryland
34   1   0        Allen Hopkins         New Jersey
35   1   0         Jeanette Lee           New York
36   1   0            Gabe Owen             Kansas
37   1   0        Brandon Shuff           Virginia
38   1   0    Vivian Villarreal              Texas
39   1   0         Billy Thorpe               Ohio
40   0   1           Buddy Hall           Illinois
41   0   1       Johan Ruijsink       Netherlands1
0   17   0         Ralf Souquet            Germany
1   15   0         Mika Immonen            Finland
2   12   0         Niels Feijen        Netherlands
3   11   0          Steve Davis            England
4    8   1       Oliver Ortmann            Germany
5    8   0      Darren Appleton            England
6    8   0    Nick van den Berg        Netherlands
7    6   3        Marcus Chamat             Sweden
8    4   0           Karl Boyes            England
9    4   0         Steve Knight            England
10   3   0        Thomas Engert            Germany
11   3   0            Mark Gray            England
12   3   0     Thorsten Hohmann            Germany
13   2   2            Alex Lely        Netherlands
14   2   0        Albin Ouschan            Austria
15   2   0           Tony Drago              Malta
16   2   0   Nick Ekonomopoulos             Greece
17   2   0        Chris Melling            England
18   2   0    Ronnie O'Sullivan            England
19   2   0          Daryl Peach            England
20   2   0            Tom Storm             Sweden
21   2   0          Jimmy White            England
22   2   0        David Alcaide              Spain
23   2   0          Jayson Shaw           Scotland
24   1   0         Tommy Donlon            Ireland
25   1   0      Vincent Facquet             France
26   1   0       Allison Fisher            England
27   1   0         Alex Higgins   Northern Ireland
28   1   0           Raj Hundal            England
29   1   0          Lee Kendall            England
30   1   0          Imran Majid            England
31   1   0        Fabio Petroni              Italy
32   1   0      Andy Richardson            England
33   1   0      Franziska Stark            Germany
34   1   0  Konstantin Stepanov             Russia
35   1   0           Lee Tucker            England
36   1   0        Joshua Filler            Germany
37   0   7       Johan Ruijsink        Netherlands

In [150]:
# Get rid of numbers at end of locations
f[f.Location.str.contains('[\d]')]

    P  NP              Name        Location
6   5   1  Charlie Williams    South Korea1
30  1   0        Paul Gerni   New Jersey[3]
41  0   1    Johan Ruijsink    Netherlands1

In [151]:
# regex to remove any number or bracket
f.Location = f.Location.str.replace('\d','')
f.Location = f.Location.str.replace('[','')
f.Location = f.Location.str.replace(']','')

In [152]:
#fix oscar's name
f.loc[f.Name=='Óscar Domínguez','Name']='Oscar Dominguez'

In [153]:
import numpy as np

In [154]:
#get rid of all non playing captains
f.loc[f.P==0,'P']=np.nan
f = f.dropna()

In [158]:
f

       P  NP                 Name           Location
0   17.0   0        Johnny Archer            Georgia
1   14.0   0      Earl Strickland     North Carolina
2   11.0   0    Shane Van Boening       South Dakota
3   10.0   0        Rodney Morris         California
4    9.0   0          Corey Deuel         California
5    7.0   0         Jeremy Jones              Texas
6    5.0   1     Charlie Williams        South Korea
7    5.0   0         Dennis Hatch           New York
8    4.0   4          Nick Varner           Kentucky
9    4.0   0        Mike Dechaine              Maine
10   3.0   1        Kim Davenport           Oklahoma
11   3.0   0       Justin Bergman           Illinois
12   3.0   0          James Rempe       Pennsylvania
13   3.0   0      Skyler Woodward           Kentucky
14   2.0   3          Mark Wilson           Missouri
15   2.0   0           Lou Butera       Pennsylvania
16   2.0   0     Michael Coltrain     North Carolina
17   2.0   0      Shannon Daulton           Kentucky
18   2.0   0        Mike Gulyassy               Ohio
19   2.0   0         Bobby Hunter           Michigan
20   2.0   0          Mike Massey          Tennessee
21   2.0   0          Reed Pierce        Mississippi
22   2.0   0         Shawn Putnam       Pennsylvania
23   2.0   0          Tony Robles           New York
24   2.0   0         John Schmidt         California
25   2.0   0          Dallas West           Illinois
26   2.0   0      Oscar Dominguez         California
27   1.0   1           C.J. Wiley              Texas
28   1.0   0           Mike Davis     North Carolina
29   1.0   0          John DiToro            Florida
30   1.0   0           Paul Gerni         New Jersey
31   1.0   0        Roger Griffis              Texas
32   1.0   0          Justin Hall           Illinois
33   1.0   0       Danny Harriman           Maryland
34   1.0   0        Allen Hopkins         New Jersey
35   1.0   0         Jeanette Lee           New York
36   1.0   0            Gabe Owen             Kansas
37   1.0   0        Brandon Shuff           Virginia
38   1.0   0    Vivian Villarreal              Texas
39   1.0   0         Billy Thorpe               Ohio
0   17.0   0         Ralf Souquet            Germany
1   15.0   0         Mika Immonen            Finland
2   12.0   0         Niels Feijen        Netherlands
3   11.0   0          Steve Davis            England
4    8.0   1       Oliver Ortmann            Germany
5    8.0   0      Darren Appleton            England
6    8.0   0    Nick van den Berg        Netherlands
7    6.0   3        Marcus Chamat             Sweden
8    4.0   0           Karl Boyes            England
9    4.0   0         Steve Knight            England
10   3.0   0        Thomas Engert            Germany
11   3.0   0            Mark Gray            England
12   3.0   0     Thorsten Hohmann            Germany
13   2.0   2            Alex Lely        Netherlands
14   2.0   0        Albin Ouschan            Austria
15   2.0   0           Tony Drago              Malta
16   2.0   0   Nick Ekonomopoulos             Greece
17   2.0   0        Chris Melling            England
18   2.0   0    Ronnie O'Sullivan            England
19   2.0   0          Daryl Peach            England
20   2.0   0            Tom Storm             Sweden
21   2.0   0          Jimmy White            England
22   2.0   0        David Alcaide              Spain
23   2.0   0          Jayson Shaw           Scotland
24   1.0   0         Tommy Donlon            Ireland
25   1.0   0      Vincent Facquet             France
26   1.0   0       Allison Fisher            England
27   1.0   0         Alex Higgins   Northern Ireland
28   1.0   0           Raj Hundal            England
29   1.0   0          Lee Kendall            England
30   1.0   0          Imran Majid            England
31   1.0   0        Fabio Petroni              Italy
32   1.0   0      Andy Richardson            England
33   1.0   0      Franziska Stark            Germany
34   1.0   0  Konstantin Stepanov             Russia
35   1.0   0           Lee Tucker            England
36   1.0   0        Joshua Filler            Germany

In [155]:
us = f.iloc[:40]

In [159]:
eu = f.iloc[40:]

In [160]:
eu

       P  NP                 Name           Location
0   17.0   0         Ralf Souquet            Germany
1   15.0   0         Mika Immonen            Finland
2   12.0   0         Niels Feijen        Netherlands
3   11.0   0          Steve Davis            England
4    8.0   1       Oliver Ortmann            Germany
5    8.0   0      Darren Appleton            England
6    8.0   0    Nick van den Berg        Netherlands
7    6.0   3        Marcus Chamat             Sweden
8    4.0   0           Karl Boyes            England
9    4.0   0         Steve Knight            England
10   3.0   0        Thomas Engert            Germany
11   3.0   0            Mark Gray            England
12   3.0   0     Thorsten Hohmann            Germany
13   2.0   2            Alex Lely        Netherlands
14   2.0   0        Albin Ouschan            Austria
15   2.0   0           Tony Drago              Malta
16   2.0   0   Nick Ekonomopoulos             Greece
17   2.0   0        Chris Melling            England
18   2.0   0    Ronnie O'Sullivan            England
19   2.0   0          Daryl Peach            England
20   2.0   0            Tom Storm             Sweden
21   2.0   0          Jimmy White            England
22   2.0   0        David Alcaide              Spain
23   2.0   0          Jayson Shaw           Scotland
24   1.0   0         Tommy Donlon            Ireland
25   1.0   0      Vincent Facquet             France
26   1.0   0       Allison Fisher            England
27   1.0   0         Alex Higgins   Northern Ireland
28   1.0   0           Raj Hundal            England
29   1.0   0          Lee Kendall            England
30   1.0   0          Imran Majid            England
31   1.0   0        Fabio Petroni              Italy
32   1.0   0      Andy Richardson            England
33   1.0   0      Franziska Stark            Germany
34   1.0   0  Konstantin Stepanov             Russia
35   1.0   0           Lee Tucker            England
36   1.0   0        Joshua Filler            Germany

In [165]:
us['Team']='America'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [166]:
eu['Team']='Europe'

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [167]:
f = pd.concat([us,eu])

In [168]:
f.drop('NP',axis=1,inplace=True)

In [169]:
f.rename(columns={'P':'Appearances'},inplace=True)

In [170]:
f = f[['Name', 'Location','Team','Appearances']]

In [171]:
f

                   Name           Location     Team  Appearances
0         Johnny Archer            Georgia  America         17.0
1       Earl Strickland     North Carolina  America         14.0
2     Shane Van Boening       South Dakota  America         11.0
3         Rodney Morris         California  America         10.0
4           Corey Deuel         California  America          9.0
5          Jeremy Jones              Texas  America          7.0
6      Charlie Williams        South Korea  America          5.0
7          Dennis Hatch           New York  America          5.0
8           Nick Varner           Kentucky  America          4.0
9         Mike Dechaine              Maine  America          4.0
10        Kim Davenport           Oklahoma  America          3.0
11       Justin Bergman           Illinois  America          3.0
12          James Rempe       Pennsylvania  America          3.0
13      Skyler Woodward           Kentucky  America          3.0
14          Mark Wilson           Missouri  America          2.0
15           Lou Butera       Pennsylvania  America          2.0
16     Michael Coltrain     North Carolina  America          2.0
17      Shannon Daulton           Kentucky  America          2.0
18        Mike Gulyassy               Ohio  America          2.0
19         Bobby Hunter           Michigan  America          2.0
20          Mike Massey          Tennessee  America          2.0
21          Reed Pierce        Mississippi  America          2.0
22         Shawn Putnam       Pennsylvania  America          2.0
23          Tony Robles           New York  America          2.0
24         John Schmidt         California  America          2.0
25          Dallas West           Illinois  America          2.0
26      Oscar Dominguez         California  America          2.0
27           C.J. Wiley              Texas  America          1.0
28           Mike Davis     North Carolina  America          1.0
29          John DiToro            Florida  America          1.0
30           Paul Gerni         New Jersey  America          1.0
31        Roger Griffis              Texas  America          1.0
32          Justin Hall           Illinois  America          1.0
33       Danny Harriman           Maryland  America          1.0
34        Allen Hopkins         New Jersey  America          1.0
35         Jeanette Lee           New York  America          1.0
36            Gabe Owen             Kansas  America          1.0
37        Brandon Shuff           Virginia  America          1.0
38    Vivian Villarreal              Texas  America          1.0
39         Billy Thorpe               Ohio  America          1.0
0          Ralf Souquet            Germany   Europe         17.0
1          Mika Immonen            Finland   Europe         15.0
2          Niels Feijen        Netherlands   Europe         12.0
3           Steve Davis            England   Europe         11.0
4        Oliver Ortmann            Germany   Europe          8.0
5       Darren Appleton            England   Europe          8.0
6     Nick van den Berg        Netherlands   Europe          8.0
7         Marcus Chamat             Sweden   Europe          6.0
8            Karl Boyes            England   Europe          4.0
9          Steve Knight            England   Europe          4.0
10        Thomas Engert            Germany   Europe          3.0
11            Mark Gray            England   Europe          3.0
12     Thorsten Hohmann            Germany   Europe          3.0
13            Alex Lely        Netherlands   Europe          2.0
14        Albin Ouschan            Austria   Europe          2.0
15           Tony Drago              Malta   Europe          2.0
16   Nick Ekonomopoulos             Greece   Europe          2.0
17        Chris Melling            England   Europe          2.0
18    Ronnie O'Sullivan            England   Europe          2.0
19          Daryl Peach            England   Europe          2.0
20            Tom Storm             Sweden   Europe          2.0
21          Jimmy White            England   Europe          2.0
22        David Alcaide              Spain   Europe          2.0
23          Jayson Shaw           Scotland   Europe          2.0
24         Tommy Donlon            Ireland   Europe          1.0
25      Vincent Facquet             France   Europe          1.0
26       Allison Fisher            England   Europe          1.0
27         Alex Higgins   Northern Ireland   Europe          1.0
28           Raj Hundal            England   Europe          1.0
29          Lee Kendall            England   Europe          1.0
30          Imran Majid            England   Europe          1.0
31        Fabio Petroni              Italy   Europe          1.0
32      Andy Richardson            England   Europe          1.0
33      Franziska Stark            Germany   Europe          1.0
34  Konstantin Stepanov             Russia   Europe          1.0
35           Lee Tucker            England   Europe          1.0
36        Joshua Filler            Germany   Europe          1.0

In [172]:
# f.to_sql('player',con,index=False,if_exists='replace')